<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260219185936 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create nursing_concurrency table for nursing module stage 1';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE nursing_concurrency (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, admission_record_id INT NOT NULL, user_id INT NOT NULL, session_id VARCHAR(128) NOT NULL, locked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_nursing_concurrency_admission ON nursing_concurrency (admission_record_id)');
        $this->addSql('CREATE INDEX idx_nursing_concurrency_locked_at ON nursing_concurrency (locked_at)');
        $this->addSql('COMMENT ON COLUMN nursing_concurrency.locked_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE nursing_concurrency');
    }
}
