<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260219194000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create nursing stage 3-8 tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE nursing_transfer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, admission_record_id INT NOT NULL, origin_service_id INT NOT NULL, destination_service_id INT NOT NULL, requested_by_user_id INT NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_by_user_id INT DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_NT_AR ON nursing_transfer (admission_record_id)');
        $this->addSql('CREATE INDEX IDX_NT_OS ON nursing_transfer (origin_service_id)');
        $this->addSql('CREATE INDEX IDX_NT_DS ON nursing_transfer (destination_service_id)');
        $this->addSql('COMMENT ON COLUMN nursing_transfer.requested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN nursing_transfer.cancelled_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('CREATE TABLE nursing_discharge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, admission_record_id INT NOT NULL, discharge_type VARCHAR(30) NOT NULL, condition_status VARCHAR(20) NOT NULL, discharged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_by_user_id INT DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ND_AR ON nursing_discharge (admission_record_id)');
        $this->addSql('COMMENT ON COLUMN nursing_discharge.discharged_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN nursing_discharge.cancelled_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('CREATE TABLE nursing_prescription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, admission_record_id INT NOT NULL, prescribed_by_id INT NOT NULL, prescribed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, complement TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_NP_AR ON nursing_prescription (admission_record_id)');
        $this->addSql('CREATE INDEX IDX_NP_PB ON nursing_prescription (prescribed_by_id)');
        $this->addSql('COMMENT ON COLUMN nursing_prescription.prescribed_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('CREATE TABLE nursing_prescription_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prescription_id INT NOT NULL, article_code VARCHAR(60) NOT NULL, article_name VARCHAR(255) NOT NULL, dose VARCHAR(100) NOT NULL, route VARCHAR(100) NOT NULL, frequency VARCHAR(100) NOT NULL, quantity INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_NPI_P ON nursing_prescription_item (prescription_id)');

        $this->addSql('CREATE TABLE nursing_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, admission_record_id INT NOT NULL, ordered_by_id INT NOT NULL, ordered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_type VARCHAR(30) NOT NULL, description TEXT NOT NULL, status VARCHAR(20) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_NO_AR ON nursing_order (admission_record_id)');
        $this->addSql('CREATE INDEX IDX_NO_OB ON nursing_order (ordered_by_id)');
        $this->addSql('COMMENT ON COLUMN nursing_order.ordered_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('CREATE TABLE nursing_charge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, admission_record_id INT NOT NULL, charge_type VARCHAR(20) NOT NULL, reference_id INT DEFAULT NULL, payload JSON DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_NC_AR2 ON nursing_charge (admission_record_id)');
        $this->addSql('COMMENT ON COLUMN nursing_charge.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN nursing_charge.updated_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('CREATE TABLE nursing_return (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, admission_record_id INT NOT NULL, item_name VARCHAR(120) NOT NULL, quantity INT NOT NULL, reason TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_NR_AR ON nursing_return (admission_record_id)');
        $this->addSql('COMMENT ON COLUMN nursing_return.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN nursing_return.cancelled_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('ALTER TABLE nursing_transfer ADD CONSTRAINT FK_NT_AR FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_transfer ADD CONSTRAINT FK_NT_OS FOREIGN KEY (origin_service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_transfer ADD CONSTRAINT FK_NT_DS FOREIGN KEY (destination_service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE nursing_discharge ADD CONSTRAINT FK_ND_AR FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE nursing_prescription ADD CONSTRAINT FK_NP_AR FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_prescription ADD CONSTRAINT FK_NP_PB FOREIGN KEY (prescribed_by_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_prescription_item ADD CONSTRAINT FK_NPI_P FOREIGN KEY (prescription_id) REFERENCES nursing_prescription (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE nursing_order ADD CONSTRAINT FK_NO_AR FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_order ADD CONSTRAINT FK_NO_OB FOREIGN KEY (ordered_by_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE nursing_charge ADD CONSTRAINT FK_NC_AR2 FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_return ADD CONSTRAINT FK_NR_AR FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE nursing_transfer DROP CONSTRAINT FK_NT_AR');
        $this->addSql('ALTER TABLE nursing_transfer DROP CONSTRAINT FK_NT_OS');
        $this->addSql('ALTER TABLE nursing_transfer DROP CONSTRAINT FK_NT_DS');
        $this->addSql('ALTER TABLE nursing_discharge DROP CONSTRAINT FK_ND_AR');
        $this->addSql('ALTER TABLE nursing_prescription DROP CONSTRAINT FK_NP_AR');
        $this->addSql('ALTER TABLE nursing_prescription DROP CONSTRAINT FK_NP_PB');
        $this->addSql('ALTER TABLE nursing_prescription_item DROP CONSTRAINT FK_NPI_P');
        $this->addSql('ALTER TABLE nursing_order DROP CONSTRAINT FK_NO_AR');
        $this->addSql('ALTER TABLE nursing_order DROP CONSTRAINT FK_NO_OB');
        $this->addSql('ALTER TABLE nursing_charge DROP CONSTRAINT FK_NC_AR2');
        $this->addSql('ALTER TABLE nursing_return DROP CONSTRAINT FK_NR_AR');

        $this->addSql('DROP TABLE nursing_transfer');
        $this->addSql('DROP TABLE nursing_discharge');
        $this->addSql('DROP TABLE nursing_prescription_item');
        $this->addSql('DROP TABLE nursing_prescription');
        $this->addSql('DROP TABLE nursing_order');
        $this->addSql('DROP TABLE nursing_charge');
        $this->addSql('DROP TABLE nursing_return');
    }
}
