<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260221030322 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE account_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE account_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE admission_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bed_assignment_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bed_patient_assignment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE care_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE emergency_admission_complement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE emergency_admission_complement_detail_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE insurance_plan_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE patient_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE patient_account_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE payment_account_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE payment_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE triage_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE warehouse_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE account_status (id INT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE account_type (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE admission_status (id INT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE bed_assignment_status (id INT NOT NULL, name VARCHAR(45) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE bed_patient_assignment (id INT NOT NULL, patient_id INT NOT NULL, bed_id INT NOT NULL, bed_assignment_status_id INT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B78051D86B899279 ON bed_patient_assignment (patient_id)');
        $this->addSql('CREATE INDEX IDX_B78051D888688BB9 ON bed_patient_assignment (bed_id)');
        $this->addSql('CREATE INDEX IDX_B78051D87AA131EF ON bed_patient_assignment (bed_assignment_status_id)');
        $this->addSql('CREATE TABLE care_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, route VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE emergency_admission_complement (id INT NOT NULL, admission_record_id INT NOT NULL, emergency_consultation_type_id INT DEFAULT NULL, company_agreement_id INT DEFAULT NULL, triage_category_id INT DEFAULT NULL, notice_police BOOLEAN DEFAULT false NOT NULL, accompanied_by VARCHAR(255) DEFAULT NULL, arrived_by VARCHAR(255) DEFAULT NULL, accident_location VARCHAR(255) DEFAULT NULL, accident_type VARCHAR(255) DEFAULT NULL, other_consultation_type VARCHAR(255) DEFAULT NULL, triage_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, code_blue BOOLEAN DEFAULT false NOT NULL, discharge_notes TEXT DEFAULT NULL, discharge_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, discharge_user_role VARCHAR(150) DEFAULT NULL, discharge_update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, discharge_update_user_role VARCHAR(150) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_61F222FBBCA2BFC5 ON emergency_admission_complement (admission_record_id)');
        $this->addSql('CREATE INDEX IDX_61F222FBFB506460 ON emergency_admission_complement (emergency_consultation_type_id)');
        $this->addSql('CREATE INDEX IDX_61F222FBDA44C1E5 ON emergency_admission_complement (company_agreement_id)');
        $this->addSql('CREATE INDEX IDX_61F222FBC74E6A32 ON emergency_admission_complement (triage_category_id)');
        $this->addSql('CREATE TABLE emergency_admission_complement_detail (id INT NOT NULL, emergency_admission_complement_id INT NOT NULL, article_id INT DEFAULT NULL, article_package_id INT DEFAULT NULL, service_package_id INT DEFAULT NULL, status INT DEFAULT NULL, entry_date DATE DEFAULT NULL, is_package BOOLEAN DEFAULT false NOT NULL, article_quantity INT DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, comment_date DATE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4A46C1552BD18C70 ON emergency_admission_complement_detail (emergency_admission_complement_id)');
        $this->addSql('CREATE INDEX IDX_4A46C1557294869C ON emergency_admission_complement_detail (article_id)');
        $this->addSql('CREATE INDEX IDX_4A46C155C8957A7E ON emergency_admission_complement_detail (article_package_id)');
        $this->addSql('CREATE INDEX IDX_4A46C155621D924B ON emergency_admission_complement_detail (service_package_id)');
        $this->addSql('CREATE TABLE insurance_plan (id INT NOT NULL, cancellation_user_id INT DEFAULT NULL, parent_plan_id INT DEFAULT NULL, branch_payer_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, is_package BOOLEAN DEFAULT false NOT NULL, is_disabled BOOLEAN DEFAULT false NOT NULL, is_telemedicine BOOLEAN DEFAULT NULL, cancellation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_37B14D4D28DB158 ON insurance_plan (cancellation_user_id)');
        $this->addSql('CREATE INDEX IDX_37B14D49AD176DD ON insurance_plan (parent_plan_id)');
        $this->addSql('CREATE INDEX IDX_37B14D426D9006A ON insurance_plan (branch_payer_id)');
        $this->addSql('COMMENT ON COLUMN insurance_plan.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN insurance_plan.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE patient (id INT NOT NULL, person_id INT NOT NULL, tutor_id INT DEFAULT NULL, payer_id INT NOT NULL, agreement_id INT DEFAULT NULL, insurance_plan_id INT DEFAULT NULL, care_type_id INT NOT NULL, origin_id INT DEFAULT NULL, external_referrer_id INT DEFAULT NULL, professional_id INT DEFAULT NULL, requesting_company_id INT DEFAULT NULL, event_number INT DEFAULT NULL, care_number INT DEFAULT NULL, admission_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_external BOOLEAN DEFAULT false NOT NULL, external_professional VARCHAR(150) DEFAULT NULL, exam_order VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1ADAD7EB217BBB47 ON patient (person_id)');
        $this->addSql('CREATE INDEX IDX_1ADAD7EB208F64F1 ON patient (tutor_id)');
        $this->addSql('CREATE INDEX IDX_1ADAD7EBC17AD9A9 ON patient (payer_id)');
        $this->addSql('CREATE INDEX IDX_1ADAD7EB24890B2B ON patient (agreement_id)');
        $this->addSql('CREATE INDEX IDX_1ADAD7EB5B8273E ON patient (insurance_plan_id)');
        $this->addSql('CREATE INDEX IDX_1ADAD7EB852D12A6 ON patient (care_type_id)');
        $this->addSql('CREATE INDEX IDX_1ADAD7EB56A273CC ON patient (origin_id)');
        $this->addSql('CREATE INDEX IDX_1ADAD7EB114B6FAC ON patient (external_referrer_id)');
        $this->addSql('CREATE INDEX IDX_1ADAD7EBDB77003 ON patient (professional_id)');
        $this->addSql('CREATE INDEX IDX_1ADAD7EBE3FB3114 ON patient (requesting_company_id)');
        $this->addSql('COMMENT ON COLUMN patient.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN patient.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE patient_account (id INT NOT NULL, patient_id INT NOT NULL, account_status_id INT DEFAULT NULL, modified_by_member_id INT DEFAULT NULL, total_account NUMERIC(12, 2) DEFAULT NULL, affected_account NUMERIC(12, 2) DEFAULT NULL, question_one INT DEFAULT NULL, question_two INT DEFAULT NULL, total_pre_account NUMERIC(12, 2) DEFAULT NULL, pre_account_number INT DEFAULT NULL, total_discount NUMERIC(12, 2) DEFAULT NULL, balance_correction_rut INT DEFAULT NULL, account_balance NUMERIC(10, 2) DEFAULT NULL, total_packaged_account NUMERIC(12, 2) DEFAULT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2055034F6B899279 ON patient_account (patient_id)');
        $this->addSql('CREATE INDEX IDX_2055034F498DD8E6 ON patient_account (account_status_id)');
        $this->addSql('CREATE INDEX IDX_2055034F24151A9B ON patient_account (modified_by_member_id)');
        $this->addSql('CREATE TABLE payment_account (id INT NOT NULL, patient_account_id INT NOT NULL, patient_id INT DEFAULT NULL, payment_status_id INT DEFAULT NULL, created_by_member_id INT DEFAULT NULL, cancelled_by_member_id INT DEFAULT NULL, cash_register_location_id INT DEFAULT NULL, sub_company_id INT DEFAULT NULL, difference_reason_id INT DEFAULT NULL, payment_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_number BIGINT DEFAULT NULL, tax INT DEFAULT NULL, amount NUMERIC(12, 2) DEFAULT NULL, document_status_id INT DEFAULT NULL, installment VARCHAR(11) DEFAULT NULL, scheduled_payment_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancellation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancellation_reason TEXT DEFAULT NULL, regularization_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, regularization_notes TEXT DEFAULT NULL, difference_amount NUMERIC(10, 2) DEFAULT NULL, price_variance NUMERIC(10, 2) DEFAULT NULL, is_collection BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_647F584E2DABF955 ON payment_account (patient_account_id)');
        $this->addSql('CREATE INDEX IDX_647F584E6B899279 ON payment_account (patient_id)');
        $this->addSql('CREATE INDEX IDX_647F584E28DE2F95 ON payment_account (payment_status_id)');
        $this->addSql('CREATE INDEX IDX_647F584E2F92D693 ON payment_account (created_by_member_id)');
        $this->addSql('CREATE INDEX IDX_647F584EFA4FB431 ON payment_account (cancelled_by_member_id)');
        $this->addSql('CREATE INDEX IDX_647F584E39F50F9A ON payment_account (cash_register_location_id)');
        $this->addSql('CREATE INDEX IDX_647F584EBB50891B ON payment_account (sub_company_id)');
        $this->addSql('CREATE INDEX IDX_647F584E7EDE4786 ON payment_account (difference_reason_id)');
        $this->addSql('CREATE TABLE payment_status (id INT NOT NULL, name VARCHAR(45) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE triage_category (id INT NOT NULL, name VARCHAR(45) NOT NULL, color VARCHAR(45) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE warehouse_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE bed_patient_assignment ADD CONSTRAINT FK_B78051D86B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bed_patient_assignment ADD CONSTRAINT FK_B78051D888688BB9 FOREIGN KEY (bed_id) REFERENCES bed (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bed_patient_assignment ADD CONSTRAINT FK_B78051D87AA131EF FOREIGN KEY (bed_assignment_status_id) REFERENCES bed_assignment_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement ADD CONSTRAINT FK_61F222FBBCA2BFC5 FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement ADD CONSTRAINT FK_61F222FBFB506460 FOREIGN KEY (emergency_consultation_type_id) REFERENCES emergency_consultation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement ADD CONSTRAINT FK_61F222FBDA44C1E5 FOREIGN KEY (company_agreement_id) REFERENCES company_agreement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement ADD CONSTRAINT FK_61F222FBC74E6A32 FOREIGN KEY (triage_category_id) REFERENCES triage_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail ADD CONSTRAINT FK_4A46C1552BD18C70 FOREIGN KEY (emergency_admission_complement_id) REFERENCES emergency_admission_complement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail ADD CONSTRAINT FK_4A46C1557294869C FOREIGN KEY (article_id) REFERENCES article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail ADD CONSTRAINT FK_4A46C155C8957A7E FOREIGN KEY (article_package_id) REFERENCES article_package (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail ADD CONSTRAINT FK_4A46C155621D924B FOREIGN KEY (service_package_id) REFERENCES service_package (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE insurance_plan ADD CONSTRAINT FK_37B14D4D28DB158 FOREIGN KEY (cancellation_user_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE insurance_plan ADD CONSTRAINT FK_37B14D49AD176DD FOREIGN KEY (parent_plan_id) REFERENCES insurance_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE insurance_plan ADD CONSTRAINT FK_37B14D426D9006A FOREIGN KEY (branch_payer_id) REFERENCES branch_payer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EB217BBB47 FOREIGN KEY (person_id) REFERENCES "person" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EB208F64F1 FOREIGN KEY (tutor_id) REFERENCES "person" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EBC17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EB24890B2B FOREIGN KEY (agreement_id) REFERENCES agreement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EB5B8273E FOREIGN KEY (insurance_plan_id) REFERENCES insurance_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EB852D12A6 FOREIGN KEY (care_type_id) REFERENCES care_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EB56A273CC FOREIGN KEY (origin_id) REFERENCES maintainer_origin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EB114B6FAC FOREIGN KEY (external_referrer_id) REFERENCES external_referrer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EBDB77003 FOREIGN KEY (professional_id) REFERENCES professional (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EBE3FB3114 FOREIGN KEY (requesting_company_id) REFERENCES requesting_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient_account ADD CONSTRAINT FK_2055034F6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient_account ADD CONSTRAINT FK_2055034F498DD8E6 FOREIGN KEY (account_status_id) REFERENCES account_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient_account ADD CONSTRAINT FK_2055034F24151A9B FOREIGN KEY (modified_by_member_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT FK_647F584E2DABF955 FOREIGN KEY (patient_account_id) REFERENCES patient_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT FK_647F584E6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT FK_647F584E28DE2F95 FOREIGN KEY (payment_status_id) REFERENCES payment_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT FK_647F584E2F92D693 FOREIGN KEY (created_by_member_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT FK_647F584EFA4FB431 FOREIGN KEY (cancelled_by_member_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT FK_647F584E39F50F9A FOREIGN KEY (cash_register_location_id) REFERENCES cash_register_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT FK_647F584EBB50891B FOREIGN KEY (sub_company_id) REFERENCES sub_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT FK_647F584E7EDE4786 FOREIGN KEY (difference_reason_id) REFERENCES difference_reason (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdb217bbb47');
        $this->addSql('DROP INDEX idx_a1a74bdb217bbb47');
        $this->addSql('ALTER TABLE admission_record ADD admission_status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD branch_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD professional_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD cancellation_reason_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD specialty_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD insurance_plan_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD origin_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD account_type_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD bed_patient_assignment_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD patient_account_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD admission_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD pre_admission_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD cancellation_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD number INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD is_surgical_admission BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE admission_record ADD has_medical_order BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE admission_record ADD notes VARCHAR(240) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD emergency_notice VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD emergency_phone VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD medical_order_file VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD other_origin VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD cancellation_notes VARCHAR(2000) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD with_fees BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE admission_record ADD dau INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD referring_doctor VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record DROP status');
        $this->addSql('ALTER TABLE admission_record RENAME COLUMN person_id TO patient_id');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDB6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDB9AA8CA74 FOREIGN KEY (admission_status_id) REFERENCES admission_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDBDCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDBDB77003 FOREIGN KEY (professional_id) REFERENCES professional (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDB8453C906 FOREIGN KEY (cancellation_reason_id) REFERENCES cancellation_reason (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDB9A353316 FOREIGN KEY (specialty_id) REFERENCES specialty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDB5B8273E FOREIGN KEY (insurance_plan_id) REFERENCES insurance_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDB56A273CC FOREIGN KEY (origin_id) REFERENCES maintainer_origin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDBC6798DB FOREIGN KEY (account_type_id) REFERENCES account_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDBABC34E3A FOREIGN KEY (bed_patient_assignment_id) REFERENCES bed_patient_assignment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDB2DABF955 FOREIGN KEY (patient_account_id) REFERENCES patient_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A1A74BDB6B899279 ON admission_record (patient_id)');
        $this->addSql('CREATE INDEX IDX_A1A74BDB9AA8CA74 ON admission_record (admission_status_id)');
        $this->addSql('CREATE INDEX IDX_A1A74BDBDCD6CC49 ON admission_record (branch_id)');
        $this->addSql('CREATE INDEX IDX_A1A74BDBDB77003 ON admission_record (professional_id)');
        $this->addSql('CREATE INDEX IDX_A1A74BDB8453C906 ON admission_record (cancellation_reason_id)');
        $this->addSql('CREATE INDEX IDX_A1A74BDB9A353316 ON admission_record (specialty_id)');
        $this->addSql('CREATE INDEX IDX_A1A74BDB5B8273E ON admission_record (insurance_plan_id)');
        $this->addSql('CREATE INDEX IDX_A1A74BDB56A273CC ON admission_record (origin_id)');
        $this->addSql('CREATE INDEX IDX_A1A74BDBC6798DB ON admission_record (account_type_id)');
        $this->addSql('CREATE INDEX IDX_A1A74BDBABC34E3A ON admission_record (bed_patient_assignment_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A1A74BDB2DABF955 ON admission_record (patient_account_id)');
        $this->addSql('ALTER TABLE company_agreement ADD code INT DEFAULT NULL');
        $this->addSql('ALTER TABLE diagnosis ADD parent_diagnosis_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE diagnosis ADD code VARCHAR(6) DEFAULT NULL');
        $this->addSql('ALTER TABLE diagnosis ADD CONSTRAINT FK_7ED10F3D6CD0102E FOREIGN KEY (parent_diagnosis_id) REFERENCES diagnosis (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_7ED10F3D6CD0102E ON diagnosis (parent_diagnosis_id)');
        $this->addSql('ALTER TABLE maintainer_origin ADD branch_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE maintainer_origin ADD CONSTRAINT FK_23B5077CDCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_23B5077CDCD6CC49 ON maintainer_origin (branch_id)');
        $this->addSql('ALTER TABLE warehouse ADD warehouse_type_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFCE2AB99E6 FOREIGN KEY (warehouse_type_id) REFERENCES warehouse_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_ECB38BFCE2AB99E6 ON warehouse (warehouse_type_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDBC6798DB');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDB9AA8CA74');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDBABC34E3A');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDB5B8273E');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDB6B899279');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDB2DABF955');
        $this->addSql('ALTER TABLE warehouse DROP CONSTRAINT FK_ECB38BFCE2AB99E6');
        $this->addSql('DROP SEQUENCE account_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE account_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE admission_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bed_assignment_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bed_patient_assignment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE care_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE emergency_admission_complement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE emergency_admission_complement_detail_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE insurance_plan_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE patient_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE patient_account_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE payment_account_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE payment_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE triage_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE warehouse_type_id_seq CASCADE');
        $this->addSql('ALTER TABLE bed_patient_assignment DROP CONSTRAINT FK_B78051D86B899279');
        $this->addSql('ALTER TABLE bed_patient_assignment DROP CONSTRAINT FK_B78051D888688BB9');
        $this->addSql('ALTER TABLE bed_patient_assignment DROP CONSTRAINT FK_B78051D87AA131EF');
        $this->addSql('ALTER TABLE emergency_admission_complement DROP CONSTRAINT FK_61F222FBBCA2BFC5');
        $this->addSql('ALTER TABLE emergency_admission_complement DROP CONSTRAINT FK_61F222FBFB506460');
        $this->addSql('ALTER TABLE emergency_admission_complement DROP CONSTRAINT FK_61F222FBDA44C1E5');
        $this->addSql('ALTER TABLE emergency_admission_complement DROP CONSTRAINT FK_61F222FBC74E6A32');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail DROP CONSTRAINT FK_4A46C1552BD18C70');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail DROP CONSTRAINT FK_4A46C1557294869C');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail DROP CONSTRAINT FK_4A46C155C8957A7E');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail DROP CONSTRAINT FK_4A46C155621D924B');
        $this->addSql('ALTER TABLE insurance_plan DROP CONSTRAINT FK_37B14D4D28DB158');
        $this->addSql('ALTER TABLE insurance_plan DROP CONSTRAINT FK_37B14D49AD176DD');
        $this->addSql('ALTER TABLE insurance_plan DROP CONSTRAINT FK_37B14D426D9006A');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EB217BBB47');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EB208F64F1');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EBC17AD9A9');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EB24890B2B');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EB5B8273E');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EB852D12A6');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EB56A273CC');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EB114B6FAC');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EBDB77003');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EBE3FB3114');
        $this->addSql('ALTER TABLE patient_account DROP CONSTRAINT FK_2055034F6B899279');
        $this->addSql('ALTER TABLE patient_account DROP CONSTRAINT FK_2055034F498DD8E6');
        $this->addSql('ALTER TABLE patient_account DROP CONSTRAINT FK_2055034F24151A9B');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT FK_647F584E2DABF955');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT FK_647F584E6B899279');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT FK_647F584E28DE2F95');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT FK_647F584E2F92D693');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT FK_647F584EFA4FB431');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT FK_647F584E39F50F9A');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT FK_647F584EBB50891B');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT FK_647F584E7EDE4786');
        $this->addSql('DROP TABLE account_status');
        $this->addSql('DROP TABLE account_type');
        $this->addSql('DROP TABLE admission_status');
        $this->addSql('DROP TABLE bed_assignment_status');
        $this->addSql('DROP TABLE bed_patient_assignment');
        $this->addSql('DROP TABLE care_type');
        $this->addSql('DROP TABLE emergency_admission_complement');
        $this->addSql('DROP TABLE emergency_admission_complement_detail');
        $this->addSql('DROP TABLE insurance_plan');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE patient_account');
        $this->addSql('DROP TABLE payment_account');
        $this->addSql('DROP TABLE payment_status');
        $this->addSql('DROP TABLE triage_category');
        $this->addSql('DROP TABLE warehouse_type');
        $this->addSql('ALTER TABLE maintainer_origin DROP CONSTRAINT FK_23B5077CDCD6CC49');
        $this->addSql('DROP INDEX IDX_23B5077CDCD6CC49');
        $this->addSql('ALTER TABLE maintainer_origin DROP branch_id');
        $this->addSql('DROP INDEX IDX_ECB38BFCE2AB99E6');
        $this->addSql('ALTER TABLE warehouse DROP warehouse_type_id');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDBDCD6CC49');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDBDB77003');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDB8453C906');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDB9A353316');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDB56A273CC');
        $this->addSql('DROP INDEX UNIQ_A1A74BDB6B899279');
        $this->addSql('DROP INDEX IDX_A1A74BDB9AA8CA74');
        $this->addSql('DROP INDEX IDX_A1A74BDBDCD6CC49');
        $this->addSql('DROP INDEX IDX_A1A74BDBDB77003');
        $this->addSql('DROP INDEX IDX_A1A74BDB8453C906');
        $this->addSql('DROP INDEX IDX_A1A74BDB9A353316');
        $this->addSql('DROP INDEX IDX_A1A74BDB5B8273E');
        $this->addSql('DROP INDEX IDX_A1A74BDB56A273CC');
        $this->addSql('DROP INDEX IDX_A1A74BDBC6798DB');
        $this->addSql('DROP INDEX IDX_A1A74BDBABC34E3A');
        $this->addSql('DROP INDEX UNIQ_A1A74BDB2DABF955');
        $this->addSql('ALTER TABLE admission_record ADD status VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE admission_record DROP admission_status_id');
        $this->addSql('ALTER TABLE admission_record DROP branch_id');
        $this->addSql('ALTER TABLE admission_record DROP professional_id');
        $this->addSql('ALTER TABLE admission_record DROP cancellation_reason_id');
        $this->addSql('ALTER TABLE admission_record DROP specialty_id');
        $this->addSql('ALTER TABLE admission_record DROP insurance_plan_id');
        $this->addSql('ALTER TABLE admission_record DROP origin_id');
        $this->addSql('ALTER TABLE admission_record DROP account_type_id');
        $this->addSql('ALTER TABLE admission_record DROP bed_patient_assignment_id');
        $this->addSql('ALTER TABLE admission_record DROP patient_account_id');
        $this->addSql('ALTER TABLE admission_record DROP admission_date');
        $this->addSql('ALTER TABLE admission_record DROP pre_admission_date');
        $this->addSql('ALTER TABLE admission_record DROP cancellation_date');
        $this->addSql('ALTER TABLE admission_record DROP number');
        $this->addSql('ALTER TABLE admission_record DROP is_surgical_admission');
        $this->addSql('ALTER TABLE admission_record DROP has_medical_order');
        $this->addSql('ALTER TABLE admission_record DROP notes');
        $this->addSql('ALTER TABLE admission_record DROP emergency_notice');
        $this->addSql('ALTER TABLE admission_record DROP emergency_phone');
        $this->addSql('ALTER TABLE admission_record DROP medical_order_file');
        $this->addSql('ALTER TABLE admission_record DROP other_origin');
        $this->addSql('ALTER TABLE admission_record DROP cancellation_notes');
        $this->addSql('ALTER TABLE admission_record DROP with_fees');
        $this->addSql('ALTER TABLE admission_record DROP dau');
        $this->addSql('ALTER TABLE admission_record DROP referring_doctor');
        $this->addSql('ALTER TABLE admission_record RENAME COLUMN patient_id TO person_id');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdb217bbb47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_a1a74bdb217bbb47 ON admission_record (person_id)');
        $this->addSql('ALTER TABLE company_agreement DROP code');
        $this->addSql('ALTER TABLE diagnosis DROP CONSTRAINT FK_7ED10F3D6CD0102E');
        $this->addSql('DROP INDEX IDX_7ED10F3D6CD0102E');
        $this->addSql('ALTER TABLE diagnosis DROP parent_diagnosis_id');
        $this->addSql('ALTER TABLE diagnosis DROP code');
    }
}
