<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260220040055 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add room.service_id FK, create nursing tables, clean up legacy tables (patient, care_type, etc.), align admission_record schema';
    }

    public function up(Schema $schema): void
    {
        // Truncate admission_record before structural changes (dev data is incompatible with new schema)
        $this->addSql('TRUNCATE TABLE admission_record CASCADE');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdb6b899279');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdbabc34e3a');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdb2dabf955');
        $this->addSql('ALTER TABLE warehouse DROP CONSTRAINT fk_ecb38bfce2ab99e6');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdb5b8273e');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdbc6798db');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdb9aa8ca74');
        $this->addSql('DROP SEQUENCE care_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE insurance_plan_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE patient_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE account_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE admission_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bed_assignment_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bed_patient_assignment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE emergency_admission_complement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE emergency_admission_complement_detail_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE triage_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE warehouse_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE account_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE patient_account_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE payment_account_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE payment_status_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE nursing_charge_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nursing_concurrency_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nursing_discharge_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nursing_order_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nursing_prescription_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nursing_prescription_item_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nursing_return_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nursing_transfer_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE nursing_charge (id INT NOT NULL, admission_record_id INT NOT NULL, charge_type VARCHAR(20) NOT NULL, reference_id INT DEFAULT NULL, payload JSON DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CCDE0787BCA2BFC5 ON nursing_charge (admission_record_id)');
        $this->addSql('COMMENT ON COLUMN nursing_charge.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN nursing_charge.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE nursing_concurrency (id INT NOT NULL, admission_record_id INT NOT NULL, user_id INT NOT NULL, session_id VARCHAR(128) NOT NULL, locked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_nursing_concurrency_locked_at ON nursing_concurrency (locked_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_nursing_concurrency_admission ON nursing_concurrency (admission_record_id)');
        $this->addSql('COMMENT ON COLUMN nursing_concurrency.locked_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE nursing_discharge (id INT NOT NULL, admission_record_id INT NOT NULL, discharge_type VARCHAR(30) NOT NULL, condition_status VARCHAR(20) NOT NULL, discharged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_by_user_id INT DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E832584EBCA2BFC5 ON nursing_discharge (admission_record_id)');
        $this->addSql('COMMENT ON COLUMN nursing_discharge.discharged_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN nursing_discharge.cancelled_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE nursing_order (id INT NOT NULL, admission_record_id INT NOT NULL, ordered_by_id INT NOT NULL, ordered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_type VARCHAR(30) NOT NULL, description TEXT NOT NULL, status VARCHAR(20) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_49DB9A9BBCA2BFC5 ON nursing_order (admission_record_id)');
        $this->addSql('CREATE INDEX IDX_49DB9A9B91FF3C4D ON nursing_order (ordered_by_id)');
        $this->addSql('COMMENT ON COLUMN nursing_order.ordered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE nursing_prescription (id INT NOT NULL, admission_record_id INT NOT NULL, prescribed_by_id INT NOT NULL, prescribed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, complement TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6C080193BCA2BFC5 ON nursing_prescription (admission_record_id)');
        $this->addSql('CREATE INDEX IDX_6C080193424D1A3F ON nursing_prescription (prescribed_by_id)');
        $this->addSql('COMMENT ON COLUMN nursing_prescription.prescribed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE nursing_prescription_item (id INT NOT NULL, prescription_id INT NOT NULL, article_code VARCHAR(60) NOT NULL, article_name VARCHAR(255) NOT NULL, dose VARCHAR(100) NOT NULL, route VARCHAR(100) NOT NULL, frequency VARCHAR(100) NOT NULL, quantity INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AB7F1AB393DB413D ON nursing_prescription_item (prescription_id)');
        $this->addSql('CREATE TABLE nursing_return (id INT NOT NULL, admission_record_id INT NOT NULL, item_name VARCHAR(120) NOT NULL, quantity INT NOT NULL, reason TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3E2B9CBCBCA2BFC5 ON nursing_return (admission_record_id)');
        $this->addSql('COMMENT ON COLUMN nursing_return.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN nursing_return.cancelled_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE nursing_transfer (id INT NOT NULL, admission_record_id INT NOT NULL, origin_service_id INT NOT NULL, destination_service_id INT NOT NULL, requested_by_user_id INT NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_by_user_id INT DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C003355CBCA2BFC5 ON nursing_transfer (admission_record_id)');
        $this->addSql('CREATE INDEX IDX_C003355C5487F3AB ON nursing_transfer (origin_service_id)');
        $this->addSql('CREATE INDEX IDX_C003355CB0653254 ON nursing_transfer (destination_service_id)');
        $this->addSql('COMMENT ON COLUMN nursing_transfer.requested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN nursing_transfer.cancelled_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE nursing_charge ADD CONSTRAINT FK_CCDE0787BCA2BFC5 FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_discharge ADD CONSTRAINT FK_E832584EBCA2BFC5 FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_order ADD CONSTRAINT FK_49DB9A9BBCA2BFC5 FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_order ADD CONSTRAINT FK_49DB9A9B91FF3C4D FOREIGN KEY (ordered_by_id) REFERENCES "person" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_prescription ADD CONSTRAINT FK_6C080193BCA2BFC5 FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_prescription ADD CONSTRAINT FK_6C080193424D1A3F FOREIGN KEY (prescribed_by_id) REFERENCES "person" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_prescription_item ADD CONSTRAINT FK_AB7F1AB393DB413D FOREIGN KEY (prescription_id) REFERENCES nursing_prescription (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_return ADD CONSTRAINT FK_3E2B9CBCBCA2BFC5 FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_transfer ADD CONSTRAINT FK_C003355CBCA2BFC5 FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_transfer ADD CONSTRAINT FK_C003355C5487F3AB FOREIGN KEY (origin_service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_transfer ADD CONSTRAINT FK_C003355CB0653254 FOREIGN KEY (destination_service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT fk_1adad7eb114b6fac');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT fk_1adad7eb208f64f1');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT fk_1adad7eb217bbb47');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT fk_1adad7eb24890b2b');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT fk_1adad7eb56a273cc');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT fk_1adad7eb5b8273e');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT fk_1adad7eb852d12a6');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT fk_1adad7ebc17ad9a9');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT fk_1adad7ebdb77003');
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT fk_1adad7ebe3fb3114');
        $this->addSql('ALTER TABLE bed_patient_assignment DROP CONSTRAINT fk_b78051d86b899279');
        $this->addSql('ALTER TABLE bed_patient_assignment DROP CONSTRAINT fk_b78051d87aa131ef');
        $this->addSql('ALTER TABLE bed_patient_assignment DROP CONSTRAINT fk_b78051d888688bb9');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT fk_647f584e28de2f95');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT fk_647f584e2dabf955');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT fk_647f584e2f92d693');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT fk_647f584e39f50f9a');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT fk_647f584e6b899279');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT fk_647f584e7ede4786');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT fk_647f584ebb50891b');
        $this->addSql('ALTER TABLE payment_account DROP CONSTRAINT fk_647f584efa4fb431');
        $this->addSql('ALTER TABLE patient_account DROP CONSTRAINT fk_2055034f24151a9b');
        $this->addSql('ALTER TABLE patient_account DROP CONSTRAINT fk_2055034f498dd8e6');
        $this->addSql('ALTER TABLE patient_account DROP CONSTRAINT fk_2055034f6b899279');
        $this->addSql('ALTER TABLE insurance_plan DROP CONSTRAINT fk_37b14d426d9006a');
        $this->addSql('ALTER TABLE insurance_plan DROP CONSTRAINT fk_37b14d49ad176dd');
        $this->addSql('ALTER TABLE insurance_plan DROP CONSTRAINT fk_37b14d4d28db158');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail DROP CONSTRAINT fk_4a46c1552bd18c70');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail DROP CONSTRAINT fk_4a46c155621d924b');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail DROP CONSTRAINT fk_4a46c1557294869c');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail DROP CONSTRAINT fk_4a46c155c8957a7e');
        $this->addSql('ALTER TABLE emergency_admission_complement DROP CONSTRAINT fk_61f222fbbca2bfc5');
        $this->addSql('ALTER TABLE emergency_admission_complement DROP CONSTRAINT fk_61f222fbc74e6a32');
        $this->addSql('ALTER TABLE emergency_admission_complement DROP CONSTRAINT fk_61f222fbda44c1e5');
        $this->addSql('ALTER TABLE emergency_admission_complement DROP CONSTRAINT fk_61f222fbfb506460');
        $this->addSql('DROP TABLE care_type');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE payment_status');
        $this->addSql('DROP TABLE bed_patient_assignment');
        $this->addSql('DROP TABLE payment_account');
        $this->addSql('DROP TABLE account_status');
        $this->addSql('DROP TABLE patient_account');
        $this->addSql('DROP TABLE warehouse_type');
        $this->addSql('DROP TABLE insurance_plan');
        $this->addSql('DROP TABLE account_type');
        $this->addSql('DROP TABLE admission_status');
        $this->addSql('DROP TABLE emergency_admission_complement_detail');
        $this->addSql('DROP TABLE triage_category');
        $this->addSql('DROP TABLE emergency_admission_complement');
        $this->addSql('DROP TABLE bed_assignment_status');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdb56a273cc');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdb8453c906');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdb9a353316');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdbdb77003');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT fk_a1a74bdbdcd6cc49');
        $this->addSql('DROP INDEX idx_a1a74bdb56a273cc');
        $this->addSql('DROP INDEX idx_a1a74bdb5b8273e');
        $this->addSql('DROP INDEX idx_a1a74bdb8453c906');
        $this->addSql('DROP INDEX idx_a1a74bdb9a353316');
        $this->addSql('DROP INDEX idx_a1a74bdb9aa8ca74');
        $this->addSql('DROP INDEX idx_a1a74bdbabc34e3a');
        $this->addSql('DROP INDEX idx_a1a74bdbc6798db');
        $this->addSql('DROP INDEX idx_a1a74bdbdb77003');
        $this->addSql('DROP INDEX idx_a1a74bdbdcd6cc49');
        $this->addSql('DROP INDEX uniq_a1a74bdb2dabf955');
        $this->addSql('DROP INDEX uniq_a1a74bdb6b899279');
        $this->addSql("ALTER TABLE admission_record ADD status VARCHAR(30) NOT NULL DEFAULT 'pending'");
        $this->addSql('ALTER TABLE admission_record ALTER COLUMN status DROP DEFAULT');
        $this->addSql('ALTER TABLE admission_record DROP admission_status_id');
        $this->addSql('ALTER TABLE admission_record DROP branch_id');
        $this->addSql('ALTER TABLE admission_record DROP professional_id');
        $this->addSql('ALTER TABLE admission_record DROP cancellation_reason_id');
        $this->addSql('ALTER TABLE admission_record DROP specialty_id');
        $this->addSql('ALTER TABLE admission_record DROP insurance_plan_id');
        $this->addSql('ALTER TABLE admission_record DROP origin_id');
        $this->addSql('ALTER TABLE admission_record DROP account_type_id');
        $this->addSql('ALTER TABLE admission_record DROP bed_patient_assignment_id');
        $this->addSql('ALTER TABLE admission_record DROP patient_account_id');
        $this->addSql('ALTER TABLE admission_record DROP admission_date');
        $this->addSql('ALTER TABLE admission_record DROP pre_admission_date');
        $this->addSql('ALTER TABLE admission_record DROP cancellation_date');
        $this->addSql('ALTER TABLE admission_record DROP number');
        $this->addSql('ALTER TABLE admission_record DROP is_surgical_admission');
        $this->addSql('ALTER TABLE admission_record DROP has_medical_order');
        $this->addSql('ALTER TABLE admission_record DROP notes');
        $this->addSql('ALTER TABLE admission_record DROP emergency_notice');
        $this->addSql('ALTER TABLE admission_record DROP emergency_phone');
        $this->addSql('ALTER TABLE admission_record DROP medical_order_file');
        $this->addSql('ALTER TABLE admission_record DROP other_origin');
        $this->addSql('ALTER TABLE admission_record DROP cancellation_notes');
        $this->addSql('ALTER TABLE admission_record DROP with_fees');
        $this->addSql('ALTER TABLE admission_record DROP dau');
        $this->addSql('ALTER TABLE admission_record DROP referring_doctor');
        $this->addSql('ALTER TABLE admission_record RENAME COLUMN patient_id TO person_id');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT FK_A1A74BDB217BBB47 FOREIGN KEY (person_id) REFERENCES "person" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_A1A74BDB217BBB47 ON admission_record (person_id)');
        $this->addSql('ALTER TABLE company_agreement DROP code');
        $this->addSql('ALTER TABLE diagnosis DROP CONSTRAINT fk_7ed10f3d6cd0102e');
        $this->addSql('DROP INDEX idx_7ed10f3d6cd0102e');
        $this->addSql('ALTER TABLE diagnosis DROP parent_diagnosis_id');
        $this->addSql('ALTER TABLE diagnosis DROP code');
        $this->addSql('ALTER TABLE maintainer_origin DROP CONSTRAINT fk_23b5077cdcd6cc49');
        $this->addSql('DROP INDEX idx_23b5077cdcd6cc49');
        $this->addSql('ALTER TABLE maintainer_origin DROP branch_id');
        $this->addSql('ALTER TABLE room ADD service_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519BED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_729F519BED5CA9E6 ON room (service_id)');
        $this->addSql('DROP INDEX idx_ecb38bfce2ab99e6');
        $this->addSql('ALTER TABLE warehouse DROP warehouse_type_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE nursing_charge_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nursing_concurrency_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nursing_discharge_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nursing_order_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nursing_prescription_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nursing_prescription_item_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nursing_return_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nursing_transfer_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE care_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE insurance_plan_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE patient_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE account_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE admission_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bed_assignment_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bed_patient_assignment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE emergency_admission_complement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE emergency_admission_complement_detail_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE triage_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE warehouse_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE account_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE patient_account_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE payment_account_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE payment_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE care_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, route VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE patient (id INT NOT NULL, person_id INT NOT NULL, tutor_id INT DEFAULT NULL, payer_id INT NOT NULL, agreement_id INT DEFAULT NULL, insurance_plan_id INT DEFAULT NULL, care_type_id INT NOT NULL, origin_id INT DEFAULT NULL, external_referrer_id INT DEFAULT NULL, professional_id INT DEFAULT NULL, requesting_company_id INT DEFAULT NULL, event_number INT DEFAULT NULL, care_number INT DEFAULT NULL, admission_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_external BOOLEAN DEFAULT false NOT NULL, external_professional VARCHAR(150) DEFAULT NULL, exam_order VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_1adad7eb114b6fac ON patient (external_referrer_id)');
        $this->addSql('CREATE INDEX idx_1adad7eb208f64f1 ON patient (tutor_id)');
        $this->addSql('CREATE INDEX idx_1adad7eb217bbb47 ON patient (person_id)');
        $this->addSql('CREATE INDEX idx_1adad7eb24890b2b ON patient (agreement_id)');
        $this->addSql('CREATE INDEX idx_1adad7eb56a273cc ON patient (origin_id)');
        $this->addSql('CREATE INDEX idx_1adad7eb5b8273e ON patient (insurance_plan_id)');
        $this->addSql('CREATE INDEX idx_1adad7eb852d12a6 ON patient (care_type_id)');
        $this->addSql('CREATE INDEX idx_1adad7ebc17ad9a9 ON patient (payer_id)');
        $this->addSql('CREATE INDEX idx_1adad7ebdb77003 ON patient (professional_id)');
        $this->addSql('CREATE INDEX idx_1adad7ebe3fb3114 ON patient (requesting_company_id)');
        $this->addSql('COMMENT ON COLUMN patient.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN patient.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE payment_status (id INT NOT NULL, name VARCHAR(45) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE bed_patient_assignment (id INT NOT NULL, patient_id INT NOT NULL, bed_id INT NOT NULL, bed_assignment_status_id INT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_b78051d86b899279 ON bed_patient_assignment (patient_id)');
        $this->addSql('CREATE INDEX idx_b78051d87aa131ef ON bed_patient_assignment (bed_assignment_status_id)');
        $this->addSql('CREATE INDEX idx_b78051d888688bb9 ON bed_patient_assignment (bed_id)');
        $this->addSql('CREATE TABLE payment_account (id INT NOT NULL, patient_account_id INT NOT NULL, patient_id INT DEFAULT NULL, payment_status_id INT DEFAULT NULL, created_by_member_id INT DEFAULT NULL, cancelled_by_member_id INT DEFAULT NULL, cash_register_location_id INT DEFAULT NULL, sub_company_id INT DEFAULT NULL, difference_reason_id INT DEFAULT NULL, payment_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_number BIGINT DEFAULT NULL, tax INT DEFAULT NULL, amount NUMERIC(12, 2) DEFAULT NULL, document_status_id INT DEFAULT NULL, installment VARCHAR(11) DEFAULT NULL, scheduled_payment_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancellation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancellation_reason TEXT DEFAULT NULL, regularization_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, regularization_notes TEXT DEFAULT NULL, difference_amount NUMERIC(10, 2) DEFAULT NULL, price_variance NUMERIC(10, 2) DEFAULT NULL, is_collection BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_647f584e28de2f95 ON payment_account (payment_status_id)');
        $this->addSql('CREATE INDEX idx_647f584e2dabf955 ON payment_account (patient_account_id)');
        $this->addSql('CREATE INDEX idx_647f584e2f92d693 ON payment_account (created_by_member_id)');
        $this->addSql('CREATE INDEX idx_647f584e39f50f9a ON payment_account (cash_register_location_id)');
        $this->addSql('CREATE INDEX idx_647f584e6b899279 ON payment_account (patient_id)');
        $this->addSql('CREATE INDEX idx_647f584e7ede4786 ON payment_account (difference_reason_id)');
        $this->addSql('CREATE INDEX idx_647f584ebb50891b ON payment_account (sub_company_id)');
        $this->addSql('CREATE INDEX idx_647f584efa4fb431 ON payment_account (cancelled_by_member_id)');
        $this->addSql('CREATE TABLE account_status (id INT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE patient_account (id INT NOT NULL, patient_id INT NOT NULL, account_status_id INT DEFAULT NULL, modified_by_member_id INT DEFAULT NULL, total_account NUMERIC(12, 2) DEFAULT NULL, affected_account NUMERIC(12, 2) DEFAULT NULL, question_one INT DEFAULT NULL, question_two INT DEFAULT NULL, total_pre_account NUMERIC(12, 2) DEFAULT NULL, pre_account_number INT DEFAULT NULL, total_discount NUMERIC(12, 2) DEFAULT NULL, balance_correction_rut INT DEFAULT NULL, account_balance NUMERIC(10, 2) DEFAULT NULL, total_packaged_account NUMERIC(12, 2) DEFAULT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_2055034f24151a9b ON patient_account (modified_by_member_id)');
        $this->addSql('CREATE INDEX idx_2055034f498dd8e6 ON patient_account (account_status_id)');
        $this->addSql('CREATE INDEX idx_2055034f6b899279 ON patient_account (patient_id)');
        $this->addSql('CREATE TABLE warehouse_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE insurance_plan (id INT NOT NULL, cancellation_user_id INT DEFAULT NULL, parent_plan_id INT DEFAULT NULL, branch_payer_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, is_package BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_disabled BOOLEAN DEFAULT false NOT NULL, is_telemedicine BOOLEAN DEFAULT NULL, cancellation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_37b14d426d9006a ON insurance_plan (branch_payer_id)');
        $this->addSql('CREATE INDEX idx_37b14d49ad176dd ON insurance_plan (parent_plan_id)');
        $this->addSql('CREATE INDEX idx_37b14d4d28db158 ON insurance_plan (cancellation_user_id)');
        $this->addSql('COMMENT ON COLUMN insurance_plan.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN insurance_plan.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE account_type (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE admission_status (id INT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE emergency_admission_complement_detail (id INT NOT NULL, emergency_admission_complement_id INT NOT NULL, article_id INT DEFAULT NULL, article_package_id INT DEFAULT NULL, service_package_id INT DEFAULT NULL, status INT DEFAULT NULL, entry_date DATE DEFAULT NULL, is_package BOOLEAN DEFAULT false NOT NULL, article_quantity INT DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, comment_date DATE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_4a46c1552bd18c70 ON emergency_admission_complement_detail (emergency_admission_complement_id)');
        $this->addSql('CREATE INDEX idx_4a46c155621d924b ON emergency_admission_complement_detail (service_package_id)');
        $this->addSql('CREATE INDEX idx_4a46c1557294869c ON emergency_admission_complement_detail (article_id)');
        $this->addSql('CREATE INDEX idx_4a46c155c8957a7e ON emergency_admission_complement_detail (article_package_id)');
        $this->addSql('CREATE TABLE triage_category (id INT NOT NULL, name VARCHAR(45) NOT NULL, color VARCHAR(45) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE emergency_admission_complement (id INT NOT NULL, admission_record_id INT NOT NULL, emergency_consultation_type_id INT DEFAULT NULL, company_agreement_id INT DEFAULT NULL, triage_category_id INT DEFAULT NULL, notice_police BOOLEAN DEFAULT false NOT NULL, accompanied_by VARCHAR(255) DEFAULT NULL, arrived_by VARCHAR(255) DEFAULT NULL, accident_location VARCHAR(255) DEFAULT NULL, accident_type VARCHAR(255) DEFAULT NULL, other_consultation_type VARCHAR(255) DEFAULT NULL, triage_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, code_blue BOOLEAN DEFAULT false NOT NULL, discharge_notes TEXT DEFAULT NULL, discharge_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, discharge_user_role VARCHAR(150) DEFAULT NULL, discharge_update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, discharge_update_user_role VARCHAR(150) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_61f222fbbca2bfc5 ON emergency_admission_complement (admission_record_id)');
        $this->addSql('CREATE INDEX idx_61f222fbc74e6a32 ON emergency_admission_complement (triage_category_id)');
        $this->addSql('CREATE INDEX idx_61f222fbda44c1e5 ON emergency_admission_complement (company_agreement_id)');
        $this->addSql('CREATE INDEX idx_61f222fbfb506460 ON emergency_admission_complement (emergency_consultation_type_id)');
        $this->addSql('CREATE TABLE bed_assignment_status (id INT NOT NULL, name VARCHAR(45) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT fk_1adad7eb114b6fac FOREIGN KEY (external_referrer_id) REFERENCES external_referrer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT fk_1adad7eb208f64f1 FOREIGN KEY (tutor_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT fk_1adad7eb217bbb47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT fk_1adad7eb24890b2b FOREIGN KEY (agreement_id) REFERENCES agreement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT fk_1adad7eb56a273cc FOREIGN KEY (origin_id) REFERENCES maintainer_origin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT fk_1adad7eb5b8273e FOREIGN KEY (insurance_plan_id) REFERENCES insurance_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT fk_1adad7eb852d12a6 FOREIGN KEY (care_type_id) REFERENCES care_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT fk_1adad7ebc17ad9a9 FOREIGN KEY (payer_id) REFERENCES payer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT fk_1adad7ebdb77003 FOREIGN KEY (professional_id) REFERENCES professional (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT fk_1adad7ebe3fb3114 FOREIGN KEY (requesting_company_id) REFERENCES requesting_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bed_patient_assignment ADD CONSTRAINT fk_b78051d86b899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bed_patient_assignment ADD CONSTRAINT fk_b78051d87aa131ef FOREIGN KEY (bed_assignment_status_id) REFERENCES bed_assignment_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bed_patient_assignment ADD CONSTRAINT fk_b78051d888688bb9 FOREIGN KEY (bed_id) REFERENCES bed (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT fk_647f584e28de2f95 FOREIGN KEY (payment_status_id) REFERENCES payment_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT fk_647f584e2dabf955 FOREIGN KEY (patient_account_id) REFERENCES patient_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT fk_647f584e2f92d693 FOREIGN KEY (created_by_member_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT fk_647f584e39f50f9a FOREIGN KEY (cash_register_location_id) REFERENCES cash_register_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT fk_647f584e6b899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT fk_647f584e7ede4786 FOREIGN KEY (difference_reason_id) REFERENCES difference_reason (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT fk_647f584ebb50891b FOREIGN KEY (sub_company_id) REFERENCES sub_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_account ADD CONSTRAINT fk_647f584efa4fb431 FOREIGN KEY (cancelled_by_member_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient_account ADD CONSTRAINT fk_2055034f24151a9b FOREIGN KEY (modified_by_member_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient_account ADD CONSTRAINT fk_2055034f498dd8e6 FOREIGN KEY (account_status_id) REFERENCES account_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE patient_account ADD CONSTRAINT fk_2055034f6b899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE insurance_plan ADD CONSTRAINT fk_37b14d426d9006a FOREIGN KEY (branch_payer_id) REFERENCES branch_payer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE insurance_plan ADD CONSTRAINT fk_37b14d49ad176dd FOREIGN KEY (parent_plan_id) REFERENCES insurance_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE insurance_plan ADD CONSTRAINT fk_37b14d4d28db158 FOREIGN KEY (cancellation_user_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail ADD CONSTRAINT fk_4a46c1552bd18c70 FOREIGN KEY (emergency_admission_complement_id) REFERENCES emergency_admission_complement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail ADD CONSTRAINT fk_4a46c155621d924b FOREIGN KEY (service_package_id) REFERENCES service_package (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail ADD CONSTRAINT fk_4a46c1557294869c FOREIGN KEY (article_id) REFERENCES article (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement_detail ADD CONSTRAINT fk_4a46c155c8957a7e FOREIGN KEY (article_package_id) REFERENCES article_package (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement ADD CONSTRAINT fk_61f222fbbca2bfc5 FOREIGN KEY (admission_record_id) REFERENCES admission_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement ADD CONSTRAINT fk_61f222fbc74e6a32 FOREIGN KEY (triage_category_id) REFERENCES triage_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement ADD CONSTRAINT fk_61f222fbda44c1e5 FOREIGN KEY (company_agreement_id) REFERENCES company_agreement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emergency_admission_complement ADD CONSTRAINT fk_61f222fbfb506460 FOREIGN KEY (emergency_consultation_type_id) REFERENCES emergency_consultation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nursing_charge DROP CONSTRAINT FK_CCDE0787BCA2BFC5');
        $this->addSql('ALTER TABLE nursing_discharge DROP CONSTRAINT FK_E832584EBCA2BFC5');
        $this->addSql('ALTER TABLE nursing_order DROP CONSTRAINT FK_49DB9A9BBCA2BFC5');
        $this->addSql('ALTER TABLE nursing_order DROP CONSTRAINT FK_49DB9A9B91FF3C4D');
        $this->addSql('ALTER TABLE nursing_prescription DROP CONSTRAINT FK_6C080193BCA2BFC5');
        $this->addSql('ALTER TABLE nursing_prescription DROP CONSTRAINT FK_6C080193424D1A3F');
        $this->addSql('ALTER TABLE nursing_prescription_item DROP CONSTRAINT FK_AB7F1AB393DB413D');
        $this->addSql('ALTER TABLE nursing_return DROP CONSTRAINT FK_3E2B9CBCBCA2BFC5');
        $this->addSql('ALTER TABLE nursing_transfer DROP CONSTRAINT FK_C003355CBCA2BFC5');
        $this->addSql('ALTER TABLE nursing_transfer DROP CONSTRAINT FK_C003355C5487F3AB');
        $this->addSql('ALTER TABLE nursing_transfer DROP CONSTRAINT FK_C003355CB0653254');
        $this->addSql('DROP TABLE nursing_charge');
        $this->addSql('DROP TABLE nursing_concurrency');
        $this->addSql('DROP TABLE nursing_discharge');
        $this->addSql('DROP TABLE nursing_order');
        $this->addSql('DROP TABLE nursing_prescription');
        $this->addSql('DROP TABLE nursing_prescription_item');
        $this->addSql('DROP TABLE nursing_return');
        $this->addSql('DROP TABLE nursing_transfer');
        $this->addSql('ALTER TABLE warehouse ADD warehouse_type_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT fk_ecb38bfce2ab99e6 FOREIGN KEY (warehouse_type_id) REFERENCES warehouse_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_ecb38bfce2ab99e6 ON warehouse (warehouse_type_id)');
        $this->addSql('ALTER TABLE maintainer_origin ADD branch_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE maintainer_origin ADD CONSTRAINT fk_23b5077cdcd6cc49 FOREIGN KEY (branch_id) REFERENCES branch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_23b5077cdcd6cc49 ON maintainer_origin (branch_id)');
        $this->addSql('ALTER TABLE diagnosis ADD parent_diagnosis_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE diagnosis ADD code VARCHAR(6) DEFAULT NULL');
        $this->addSql('ALTER TABLE diagnosis ADD CONSTRAINT fk_7ed10f3d6cd0102e FOREIGN KEY (parent_diagnosis_id) REFERENCES diagnosis (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_7ed10f3d6cd0102e ON diagnosis (parent_diagnosis_id)');
        $this->addSql('ALTER TABLE company_agreement ADD code INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record DROP CONSTRAINT FK_A1A74BDB217BBB47');
        $this->addSql('DROP INDEX IDX_A1A74BDB217BBB47');
        $this->addSql('ALTER TABLE admission_record ADD admission_status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD branch_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD professional_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD cancellation_reason_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD specialty_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD insurance_plan_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD origin_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD account_type_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD bed_patient_assignment_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD patient_account_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD admission_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD pre_admission_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD cancellation_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD number INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD is_surgical_admission BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE admission_record ADD has_medical_order BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE admission_record ADD notes VARCHAR(240) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD emergency_notice VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD emergency_phone VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD medical_order_file VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD other_origin VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD cancellation_notes VARCHAR(2000) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD with_fees BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE admission_record ADD dau INT DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record ADD referring_doctor VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE admission_record DROP status');
        $this->addSql('ALTER TABLE admission_record RENAME COLUMN person_id TO patient_id');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdb2dabf955 FOREIGN KEY (patient_account_id) REFERENCES patient_account (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdb56a273cc FOREIGN KEY (origin_id) REFERENCES maintainer_origin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdb5b8273e FOREIGN KEY (insurance_plan_id) REFERENCES insurance_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdb6b899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdb8453c906 FOREIGN KEY (cancellation_reason_id) REFERENCES cancellation_reason (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdb9a353316 FOREIGN KEY (specialty_id) REFERENCES specialty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdb9aa8ca74 FOREIGN KEY (admission_status_id) REFERENCES admission_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdbabc34e3a FOREIGN KEY (bed_patient_assignment_id) REFERENCES bed_patient_assignment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdbc6798db FOREIGN KEY (account_type_id) REFERENCES account_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdbdb77003 FOREIGN KEY (professional_id) REFERENCES professional (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_record ADD CONSTRAINT fk_a1a74bdbdcd6cc49 FOREIGN KEY (branch_id) REFERENCES branch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_a1a74bdb56a273cc ON admission_record (origin_id)');
        $this->addSql('CREATE INDEX idx_a1a74bdb5b8273e ON admission_record (insurance_plan_id)');
        $this->addSql('CREATE INDEX idx_a1a74bdb8453c906 ON admission_record (cancellation_reason_id)');
        $this->addSql('CREATE INDEX idx_a1a74bdb9a353316 ON admission_record (specialty_id)');
        $this->addSql('CREATE INDEX idx_a1a74bdb9aa8ca74 ON admission_record (admission_status_id)');
        $this->addSql('CREATE INDEX idx_a1a74bdbabc34e3a ON admission_record (bed_patient_assignment_id)');
        $this->addSql('CREATE INDEX idx_a1a74bdbc6798db ON admission_record (account_type_id)');
        $this->addSql('CREATE INDEX idx_a1a74bdbdb77003 ON admission_record (professional_id)');
        $this->addSql('CREATE INDEX idx_a1a74bdbdcd6cc49 ON admission_record (branch_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_a1a74bdb2dabf955 ON admission_record (patient_account_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_a1a74bdb6b899279 ON admission_record (patient_id)');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519BED5CA9E6');
        $this->addSql('DROP INDEX IDX_729F519BED5CA9E6');
        $this->addSql('ALTER TABLE room DROP service_id');
    }
}
