<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260201135350 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE agreement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE appointment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE article_package_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE authorization_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bed_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bed_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE blocking_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE branch_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE branch_payer_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE branch_service_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE budget_item_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "business_activity_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cancellation_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE clinic_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE consultation_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cost_center_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE country_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE department_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "education_level_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE eno_pathology_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "ethnic_group_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exam_package_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exam_package_detail_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE external_referrer_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE figure_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ges_pathology_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE group_permission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "health_insurance_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE health_insurance_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "identification_type_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_doctor_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_education_level_detail_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_insurance_administrator_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_job_position_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_location_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_medical_box_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_origin_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_origin_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "marital_status_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE medical_service_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE medical_service_bed_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE medical_service_budget_item_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE medical_service_service_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE member_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE member_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE menu_items_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "municipality_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "occupation_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pathology_article_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE payer_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE payer_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE permission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "person_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE person_address_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE professional_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE professional_rate_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "province_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "region_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "religion_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE requesting_company_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reset_password_request_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE room_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE schedule_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE service_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE service_package_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE service_package_detail_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE service_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE gender_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE specialty_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE specialty_branch_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sub_company_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE surgery_item_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "tax_affectation_type_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tenant_module_permission_override_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tenant_permission_profile_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE treatment_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE warehouse_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE warehouse_medical_service_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE agreement (id INT NOT NULL, payer_id INT DEFAULT NULL, requesting_company_id INT DEFAULT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, agreement_type VARCHAR(100) DEFAULT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, discount_percentage NUMERIC(5, 2) DEFAULT NULL, payment_term_days INT DEFAULT NULL, terms TEXT DEFAULT NULL, covered_services TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, auto_renew BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2E655A24C17AD9A9 ON agreement (payer_id)');
        $this->addSql('CREATE INDEX IDX_2E655A24E3FB3114 ON agreement (requesting_company_id)');
        $this->addSql('CREATE TABLE appointment (id INT NOT NULL, schedule_id INT NOT NULL, professional_id INT NOT NULL, consultation_type_id INT DEFAULT NULL, payer_id INT DEFAULT NULL, authorization_id INT DEFAULT NULL, cancellation_type_id INT DEFAULT NULL, appointment_number VARCHAR(50) NOT NULL, patient_name VARCHAR(100) NOT NULL, patient_rut VARCHAR(20) NOT NULL, patient_email VARCHAR(100) DEFAULT NULL, patient_phone VARCHAR(50) DEFAULT NULL, appointment_date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration_minutes INT DEFAULT 30 NOT NULL, status VARCHAR(50) NOT NULL, cancellation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancellation_reason TEXT DEFAULT NULL, reason TEXT DEFAULT NULL, observations TEXT DEFAULT NULL, is_first_time BOOLEAN DEFAULT false NOT NULL, reminder_sent BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE38F844D1CEA01A ON appointment (appointment_number)');
        $this->addSql('CREATE INDEX IDX_FE38F844A40BC2D5 ON appointment (schedule_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844DB77003 ON appointment (professional_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844804F7D71 ON appointment (consultation_type_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844C17AD9A9 ON appointment (payer_id)');
        $this->addSql('CREATE INDEX IDX_FE38F8442F8B0EB2 ON appointment (authorization_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844B0AFEE5E ON appointment (cancellation_type_id)');
        $this->addSql('CREATE TABLE article_package (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, package_type VARCHAR(100) DEFAULT NULL, package_price NUMERIC(10, 2) DEFAULT NULL, is_pre_assembled BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "authorization" (id INT NOT NULL, payer_id INT NOT NULL, service_type_id INT DEFAULT NULL, authorization_code VARCHAR(50) NOT NULL, patient_name VARCHAR(100) DEFAULT NULL, patient_rut VARCHAR(20) DEFAULT NULL, authorization_date DATE NOT NULL, expiration_date DATE DEFAULT NULL, authorized_services TEXT DEFAULT NULL, authorized_amount NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(50) NOT NULL, observations TEXT DEFAULT NULL, authorized_by VARCHAR(100) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7A6D8BEFC17AD9A9 ON "authorization" (payer_id)');
        $this->addSql('CREATE INDEX IDX_7A6D8BEFAC8DE0F ON "authorization" (service_type_id)');
        $this->addSql('CREATE TABLE bed (id INT NOT NULL, bed_type_id INT NOT NULL, room_id INT DEFAULT NULL, bed_number VARCHAR(20) NOT NULL, floor VARCHAR(50) DEFAULT NULL, wing VARCHAR(100) DEFAULT NULL, status VARCHAR(50) NOT NULL, last_maintenance_date DATE DEFAULT NULL, observations TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E647FCFF8158330E ON bed (bed_type_id)');
        $this->addSql('CREATE INDEX IDX_E647FCFF54177093 ON bed (room_id)');
        $this->addSql('CREATE TABLE bed_type (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, daily_rate NUMERIC(10, 2) DEFAULT NULL, requires_special_care BOOLEAN DEFAULT false NOT NULL, capacity INT DEFAULT 1 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE blocking_type (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, color VARCHAR(30) DEFAULT NULL, requires_approval BOOLEAN DEFAULT false NOT NULL, allows_override BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE branch (id INT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(100) DEFAULT NULL, address TEXT DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, region VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE branch_payer (id INT NOT NULL, branch_id INT NOT NULL, payer_id INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2F7A59CEDCD6CC49 ON branch_payer (branch_id)');
        $this->addSql('CREATE INDEX IDX_2F7A59CEC17AD9A9 ON branch_payer (payer_id)');
        $this->addSql('CREATE TABLE branch_service_type (id INT NOT NULL, branch_id INT NOT NULL, service_type_id INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1F793463DCD6CC49 ON branch_service_type (branch_id)');
        $this->addSql('CREATE INDEX IDX_1F793463AC8DE0F ON branch_service_type (service_type_id)');
        $this->addSql('CREATE TABLE budget_item (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, unit_price NUMERIC(10, 2) DEFAULT NULL, unit_of_measure VARCHAR(50) DEFAULT NULL, category VARCHAR(50) DEFAULT NULL, is_taxable BOOLEAN DEFAULT false NOT NULL, requires_authorization BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "business_activity" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE cancellation_type (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, requires_justification BOOLEAN DEFAULT false NOT NULL, allows_refund BOOLEAN DEFAULT false NOT NULL, affects_statistics BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE clinic (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, short_name VARCHAR(50) DEFAULT NULL, rut VARCHAR(20) DEFAULT NULL, address TEXT NOT NULL, city VARCHAR(100) DEFAULT NULL, region VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, director VARCHAR(100) DEFAULT NULL, total_beds INT DEFAULT NULL, has_emergency BOOLEAN DEFAULT false NOT NULL, has_icu BOOLEAN DEFAULT false NOT NULL, is_main_facility BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE consultation_type (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, default_duration_minutes INT DEFAULT NULL, requires_prior_appointment BOOLEAN DEFAULT false NOT NULL, is_emergency BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE cost_center (id INT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(100) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE country (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, demonym VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE department (id INT NOT NULL, branch_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(100) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CD1DE18ADCD6CC49 ON department (branch_id)');
        $this->addSql('CREATE TABLE "education_level" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value BOOLEAN DEFAULT true NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE eno_pathology (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, icd10_code VARCHAR(20) DEFAULT NULL, requires_specialist BOOLEAN DEFAULT false NOT NULL, is_chronic BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "ethnic_group" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE exam_package (id INT NOT NULL, medical_service_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, is_billable BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D3CE3EFDC61D802A ON exam_package (medical_service_id)');
        $this->addSql('CREATE TABLE exam_package_detail (id INT NOT NULL, exam_package_id INT NOT NULL, medical_service_id INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8E28E519E644D1AA ON exam_package_detail (exam_package_id)');
        $this->addSql('CREATE INDEX IDX_8E28E519C61D802A ON exam_package_detail (medical_service_id)');
        $this->addSql('CREATE TABLE external_referrer (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, short_name VARCHAR(50) DEFAULT NULL, referrer_type VARCHAR(100) DEFAULT NULL, rut VARCHAR(20) DEFAULT NULL, address TEXT DEFAULT NULL, contact_person VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, has_agreement BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE figure (id INT NOT NULL, name VARCHAR(45) NOT NULL, is_surgical_room BOOLEAN NOT NULL, is_zero BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ges_pathology (id INT NOT NULL, pathology_number VARCHAR(10) DEFAULT NULL, name VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, min_age INT DEFAULT NULL, max_age INT DEFAULT NULL, min_age_months INT DEFAULT NULL, max_age_months INT DEFAULT NULL, gender_restriction VARCHAR(20) DEFAULT NULL, guaranteed_days INT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE group_permission (id INT NOT NULL, group_id INT NOT NULL, created_by_id INT DEFAULT NULL, domain VARCHAR(100) NOT NULL, resource_id INT DEFAULT NULL, field_name VARCHAR(100) DEFAULT NULL, can_view BOOLEAN NOT NULL, can_edit BOOLEAN NOT NULL, can_delete BOOLEAN NOT NULL, constraints JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3784F318FE54D947 ON group_permission (group_id)');
        $this->addSql('CREATE INDEX IDX_3784F318B03A8386 ON group_permission (created_by_id)');
        $this->addSql('CREATE INDEX idx_group_permission_domain ON group_permission (domain)');
        $this->addSql('CREATE INDEX idx_group_permission_resource ON group_permission (domain, resource_id)');
        $this->addSql('COMMENT ON COLUMN group_permission.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "health_insurance" (id INT NOT NULL, health_insurance_type_id INT DEFAULT NULL, tax_affectation_type_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, interface_code VARCHAR(100) DEFAULT NULL, id_imed INT DEFAULT NULL, abbreviated_name VARCHAR(45) NOT NULL, is_default_value BOOLEAN DEFAULT true NOT NULL, healthcare_prevition_hl7 VARCHAR(30) DEFAULT NULL, icon VARCHAR(45) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_558804DE54CCFBDD ON "health_insurance" (health_insurance_type_id)');
        $this->addSql('CREATE INDEX IDX_558804DE588DA015 ON "health_insurance" (tax_affectation_type_id)');
        $this->addSql('CREATE TABLE health_insurance_type (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value BOOLEAN DEFAULT true NOT NULL, is_agreement BOOLEAN DEFAULT true NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "identification_type" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_doctor_type (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_education_level_detail (id INT NOT NULL, education_level_id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D867A8A7D7A5352E ON maintainer_education_level_detail (education_level_id)');
        $this->addSql('CREATE TABLE maintainer_insurance_administrator (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, rut VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_job_position (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_location (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, floor VARCHAR(50) DEFAULT NULL, building VARCHAR(50) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_medical_box (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, capacity INT DEFAULT NULL, floor VARCHAR(50) DEFAULT NULL, building VARCHAR(50) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_origin (id INT NOT NULL, origin_type_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_23B5077C703B99FE ON maintainer_origin (origin_type_id)');
        $this->addSql('CREATE TABLE maintainer_origin_type (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "marital_status" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value BOOLEAN DEFAULT true NOT NULL, marital_status_code_hl7 VARCHAR(2) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE medical_service (id INT NOT NULL, figure_id INT DEFAULT NULL, budget_item_id INT DEFAULT NULL, service_type_id INT DEFAULT NULL, sub_company_id INT DEFAULT NULL, billing_sub_company_id INT DEFAULT NULL, code VARCHAR(20) NOT NULL, fonasa_code VARCHAR(20) DEFAULT NULL, name TEXT NOT NULL, short_name VARCHAR(45) DEFAULT NULL, accounting_code_erp INT DEFAULT NULL, duration TIME(0) WITHOUT TIME ZONE DEFAULT NULL, description TEXT DEFAULT NULL, applies_surcharge BOOLEAN NOT NULL, is_imed BOOLEAN NOT NULL, imed_code VARCHAR(20) DEFAULT NULL, interface_code VARCHAR(20) DEFAULT NULL, participation INT DEFAULT NULL, is_taxed BOOLEAN NOT NULL, is_procedure BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A79F7A1C5C011B5 ON medical_service (figure_id)');
        $this->addSql('CREATE INDEX IDX_A79F7A1CD0EC18BF ON medical_service (budget_item_id)');
        $this->addSql('CREATE INDEX IDX_A79F7A1CAC8DE0F ON medical_service (service_type_id)');
        $this->addSql('CREATE INDEX IDX_A79F7A1CBB50891B ON medical_service (sub_company_id)');
        $this->addSql('CREATE INDEX IDX_A79F7A1C3395B1AC ON medical_service (billing_sub_company_id)');
        $this->addSql('CREATE TABLE medical_service_bed_type (id INT NOT NULL, medical_service_id INT NOT NULL, bed_type_id INT NOT NULL, quantity INT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EEE3D850C61D802A ON medical_service_bed_type (medical_service_id)');
        $this->addSql('CREATE INDEX IDX_EEE3D8508158330E ON medical_service_bed_type (bed_type_id)');
        $this->addSql('CREATE TABLE medical_service_budget_item (id INT NOT NULL, medical_service_id INT NOT NULL, surgery_item_id INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9E9803FBC61D802A ON medical_service_budget_item (medical_service_id)');
        $this->addSql('CREATE INDEX IDX_9E9803FBA4665449 ON medical_service_budget_item (surgery_item_id)');
        $this->addSql('CREATE TABLE medical_service_service (id INT NOT NULL, medical_service_id INT NOT NULL, service_id INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D8EE37BEC61D802A ON medical_service_service (medical_service_id)');
        $this->addSql('CREATE INDEX IDX_D8EE37BEED5CA9E6 ON medical_service_service (service_id)');
        $this->addSql('CREATE TABLE member (id INT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON member (username)');
        $this->addSql('COMMENT ON COLUMN member.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN member.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE member_group_membership (member_id INT NOT NULL, member_group_id INT NOT NULL, PRIMARY KEY(member_id, member_group_id))');
        $this->addSql('CREATE INDEX IDX_61D5C0D17597D3FE ON member_group_membership (member_id)');
        $this->addSql('CREATE INDEX IDX_61D5C0D19897AAD ON member_group_membership (member_group_id)');
        $this->addSql('CREATE TABLE member_group (id INT NOT NULL, name VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL, description VARCHAR(500) DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE1D13677153098 ON member_group (code)');
        $this->addSql('COMMENT ON COLUMN member_group.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN member_group.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE menu_items (id INT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, label VARCHAR(100) NOT NULL, route VARCHAR(255) DEFAULT NULL, icon VARCHAR(100) DEFAULT NULL, module VARCHAR(100) DEFAULT NULL, position INT NOT NULL, enabled BOOLEAN NOT NULL, visible_in_sidebar BOOLEAN NOT NULL, requires_auth BOOLEAN NOT NULL, required_roles JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_70B2CA2A727ACA70 ON menu_items (parent_id)');
        $this->addSql('CREATE TABLE "municipality" (id INT NOT NULL, province_id INT NOT NULL, name VARCHAR(100) NOT NULL, municipality_code_hl7 VARCHAR(10) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C6F56628E946114A ON "municipality" (province_id)');
        $this->addSql('CREATE TABLE "occupation" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value BOOLEAN NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pathology_article (id INT NOT NULL, ges_pathology_id INT NOT NULL, article_name VARCHAR(200) NOT NULL, article_code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, quantity INT DEFAULT 1 NOT NULL, unit_of_measure VARCHAR(50) DEFAULT NULL, unit_cost NUMERIC(10, 2) DEFAULT NULL, is_mandatory BOOLEAN DEFAULT true NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B24A1BE1541D0E27 ON pathology_article (ges_pathology_id)');
        $this->addSql('CREATE TABLE payer (id INT NOT NULL, payer_type_id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, short_name VARCHAR(50) DEFAULT NULL, rut VARCHAR(20) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, address TEXT DEFAULT NULL, discount_percentage NUMERIC(5, 2) DEFAULT NULL, payment_days INT DEFAULT NULL, requires_authorization BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_41CB5B99BEA5E0F7 ON payer (payer_type_id)');
        $this->addSql('CREATE TABLE payer_type (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, is_agreement BOOLEAN DEFAULT false NOT NULL, is_default BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE permission (id INT NOT NULL, user_id INT NOT NULL, created_by_id INT DEFAULT NULL, domain VARCHAR(100) NOT NULL, resource_id INT DEFAULT NULL, field_name VARCHAR(100) DEFAULT NULL, can_view BOOLEAN NOT NULL, can_edit BOOLEAN NOT NULL, can_delete BOOLEAN NOT NULL, constraints JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E04992AAA76ED395 ON permission (user_id)');
        $this->addSql('CREATE INDEX IDX_E04992AAB03A8386 ON permission (created_by_id)');
        $this->addSql('CREATE INDEX IDX_E04992AAA76ED395A7A91E0B ON permission (user_id, domain)');
        $this->addSql('CREATE INDEX IDX_E04992AAA7A91E0B89329D25 ON permission (domain, resource_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_permission ON permission (user_id, domain, resource_id, field_name)');
        $this->addSql('COMMENT ON COLUMN permission.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "person" (id INT NOT NULL, identification_type_id INT DEFAULT NULL, education_level_id INT DEFAULT NULL, marital_status_id INT DEFAULT NULL, occupation_id INT DEFAULT NULL, ethnic_group_id INT DEFAULT NULL, religion_id INT DEFAULT NULL, gender_id INT DEFAULT NULL, nacionality_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, identification VARCHAR(100) NOT NULL, name VARCHAR(60) NOT NULL, last_name VARCHAR(45) NOT NULL, middle_name VARCHAR(45) DEFAULT NULL, birth_date_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, death_date_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, non_medical_note TEXT DEFAULT NULL, photo_path VARCHAR(255) DEFAULT NULL, is_record_visibility BOOLEAN DEFAULT true NOT NULL, record_viewed_date_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, social_name VARCHAR(50) DEFAULT NULL, number_of_children INT DEFAULT NULL, mobile_phone VARCHAR(20) NOT NULL, work_phone VARCHAR(20) DEFAULT NULL, home_phone VARCHAR(20) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, secondary_email VARCHAR(100) DEFAULT NULL, contact_method VARCHAR(50) DEFAULT NULL, twin_number INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_34DCD176F54A83F ON "person" (identification_type_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176D7A5352E ON "person" (education_level_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176E559F9BF ON "person" (marital_status_id)');
        $this->addSql('CREATE INDEX IDX_34DCD17622C8FC20 ON "person" (occupation_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176E7EEEDB3 ON "person" (ethnic_group_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176B7850CBD ON "person" (religion_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176708A0E0 ON "person" (gender_id)');
        $this->addSql('CREATE INDEX IDX_34DCD1767949DE26 ON "person" (nacionality_id)');
        $this->addSql('COMMENT ON COLUMN "person".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "person".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "person".birth_date_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "person".death_date_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "person".record_viewed_date_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE person_address (id INT NOT NULL, id_person_id INT DEFAULT NULL, municipality_id INT DEFAULT NULL, country_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, address VARCHAR(255) NOT NULL, street_number VARCHAR(10) NOT NULL, address_details VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2FD0DC08A14E0760 ON person_address (id_person_id)');
        $this->addSql('CREATE INDEX IDX_2FD0DC08AE6F181C ON person_address (municipality_id)');
        $this->addSql('CREATE INDEX IDX_2FD0DC08F92F3E70 ON person_address (country_id)');
        $this->addSql('COMMENT ON COLUMN person_address.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE professional (id INT NOT NULL, specialty_id INT DEFAULT NULL, code VARCHAR(20) DEFAULT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, rut VARCHAR(20) NOT NULL, professional_type VARCHAR(50) DEFAULT NULL, license_number VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, mobile VARCHAR(50) DEFAULT NULL, address TEXT DEFAULT NULL, hire_date DATE DEFAULT NULL, is_external BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B3B573AA9A353316 ON professional (specialty_id)');
        $this->addSql('CREATE TABLE professional_rate (id INT NOT NULL, professional_id INT NOT NULL, service_id INT DEFAULT NULL, payer_id INT DEFAULT NULL, rate NUMERIC(10, 2) NOT NULL, effective_date DATE NOT NULL, expiration_date DATE DEFAULT NULL, observations TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CDA906E7DB77003 ON professional_rate (professional_id)');
        $this->addSql('CREATE INDEX IDX_CDA906E7ED5CA9E6 ON professional_rate (service_id)');
        $this->addSql('CREATE INDEX IDX_CDA906E7C17AD9A9 ON professional_rate (payer_id)');
        $this->addSql('CREATE TABLE "province" (id INT NOT NULL, region_id INT NOT NULL, name VARCHAR(100) NOT NULL, province_code_hl7 VARCHAR(10) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4ADAD40B98260155 ON "province" (region_id)');
        $this->addSql('CREATE TABLE "region" (id INT NOT NULL, country_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, address_state_hl7 VARCHAR(10) DEFAULT NULL, region_code_hl7 VARCHAR(10) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F62F176F92F3E70 ON "region" (country_id)');
        $this->addSql('CREATE TABLE "religion" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value BOOLEAN DEFAULT true NOT NULL, religion_code_hl7 VARCHAR(10) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE requesting_company (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, business_name VARCHAR(150) NOT NULL, trade_name VARCHAR(50) DEFAULT NULL, rut VARCHAR(20) NOT NULL, address TEXT DEFAULT NULL, contact_person VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, industry VARCHAR(100) DEFAULT NULL, number_of_employees INT DEFAULT NULL, discount_percentage NUMERIC(5, 2) DEFAULT NULL, payment_term_days INT DEFAULT NULL, has_agreement BOOLEAN DEFAULT false NOT NULL, agreement_start_date DATE DEFAULT NULL, agreement_end_date DATE DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE reset_password_request (id INT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('COMMENT ON COLUMN reset_password_request.requested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE room (id INT NOT NULL, clinic_id INT DEFAULT NULL, room_number VARCHAR(50) NOT NULL, name VARCHAR(150) NOT NULL, room_type VARCHAR(100) DEFAULT NULL, floor VARCHAR(50) DEFAULT NULL, wing VARCHAR(100) DEFAULT NULL, capacity INT DEFAULT 1 NOT NULL, daily_rate NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(50) NOT NULL, has_oxygen BOOLEAN DEFAULT false NOT NULL, has_bathroom BOOLEAN DEFAULT false NOT NULL, observations TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_729F519BCC22AD4 ON room (clinic_id)');
        $this->addSql('CREATE TABLE schedule (id INT NOT NULL, professional_id INT NOT NULL, consultation_type_id INT DEFAULT NULL, blocking_type_id INT DEFAULT NULL, schedule_date DATE NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, slot_duration_minutes INT DEFAULT 30 NOT NULL, location VARCHAR(100) DEFAULT NULL, max_appointments INT DEFAULT 1 NOT NULL, is_blocked BOOLEAN DEFAULT false NOT NULL, observations TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5A3811FBDB77003 ON schedule (professional_id)');
        $this->addSql('CREATE INDEX IDX_5A3811FB804F7D71 ON schedule (consultation_type_id)');
        $this->addSql('CREATE INDEX IDX_5A3811FB6DB2886B ON schedule (blocking_type_id)');
        $this->addSql('CREATE TABLE service (id INT NOT NULL, service_type_id INT DEFAULT NULL, specialty_id INT DEFAULT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, base_price NUMERIC(10, 2) DEFAULT NULL, estimated_duration_minutes INT DEFAULT NULL, requires_authorization BOOLEAN DEFAULT false NOT NULL, requires_specialist BOOLEAN DEFAULT false NOT NULL, is_ambulatory BOOLEAN DEFAULT false NOT NULL, fonasa_code VARCHAR(50) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E19D9AD2AC8DE0F ON service (service_type_id)');
        $this->addSql('CREATE INDEX IDX_E19D9AD29A353316 ON service (specialty_id)');
        $this->addSql('CREATE TABLE service_package (id INT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, is_billable BOOLEAN NOT NULL, is_program BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE service_package_detail (id INT NOT NULL, service_package_id INT NOT NULL, medical_service_id INT NOT NULL, quantity INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_139B51F9621D924B ON service_package_detail (service_package_id)');
        $this->addSql('CREATE INDEX IDX_139B51F9C61D802A ON service_package_detail (medical_service_id)');
        $this->addSql('CREATE TABLE service_type (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, requires_authorization BOOLEAN DEFAULT false NOT NULL, requires_bed_assignment BOOLEAN DEFAULT false NOT NULL, default_duration INT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "setting" (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, field_format VARCHAR(32) NOT NULL, field_available_value TEXT DEFAULT NULL, description TEXT DEFAULT NULL, field_default_value TEXT DEFAULT NULL, field_required BOOLEAN DEFAULT NULL, field_value TEXT DEFAULT NULL, special_attributes JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F74B898989D9B62 ON "setting" (slug)');
        $this->addSql('COMMENT ON COLUMN "setting".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "setting".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE gender (id INT NOT NULL, name VARCHAR(50) NOT NULL, code VARCHAR(10) DEFAULT NULL, is_active BOOLEAN NOT NULL, id_estado INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE specialty (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(100) DEFAULT NULL, requires_certification BOOLEAN DEFAULT false NOT NULL, default_consultation_duration INT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE specialty_branch (id INT NOT NULL, specialty_id INT NOT NULL, branch_id INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_89FD01D99A353316 ON specialty_branch (specialty_id)');
        $this->addSql('CREATE INDEX IDX_89FD01D9DCD6CC49 ON specialty_branch (branch_id)');
        $this->addSql('CREATE TABLE sub_company (id INT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(100) DEFAULT NULL, tax_id VARCHAR(50) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE surgery_item (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(100) DEFAULT NULL, unit_of_measure VARCHAR(50) DEFAULT NULL, unit_cost NUMERIC(10, 2) DEFAULT NULL, is_sterile BOOLEAN DEFAULT false NOT NULL, is_disposable BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "tax_affectation_type" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tenant_module_permission_override (id INT NOT NULL, module_name VARCHAR(100) NOT NULL, required_roles JSON NOT NULL, description VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX unique_module_permission ON tenant_module_permission_override (module_name)');
        $this->addSql('COMMENT ON COLUMN tenant_module_permission_override.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN tenant_module_permission_override.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE tenant_permission_profile (id INT NOT NULL, profile_type VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN tenant_permission_profile.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN tenant_permission_profile.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE treatment_type (id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, requires_specialist BOOLEAN DEFAULT false NOT NULL, requires_authorization BOOLEAN DEFAULT false NOT NULL, average_duration_days INT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE warehouse (id INT NOT NULL, service_id INT DEFAULT NULL, parent_warehouse_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, short_name VARCHAR(255) DEFAULT NULL, code VARCHAR(255) NOT NULL, creates_article BOOLEAN NOT NULL, is_virtual BOOLEAN NOT NULL, is_pharmacy BOOLEAN NOT NULL, is_automatic_reception BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ECB38BFCED5CA9E6 ON warehouse (service_id)');
        $this->addSql('CREATE INDEX IDX_ECB38BFCEEB1F0 ON warehouse (parent_warehouse_id)');
        $this->addSql('CREATE TABLE warehouse_medical_service (id INT NOT NULL, warehouse_id INT NOT NULL, medical_service_id INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E698EAF5080ECDE ON warehouse_medical_service (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_E698EAFC61D802A ON warehouse_medical_service (medical_service_id)');
        $this->addSql('ALTER TABLE agreement ADD CONSTRAINT FK_2E655A24C17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agreement ADD CONSTRAINT FK_2E655A24E3FB3114 FOREIGN KEY (requesting_company_id) REFERENCES requesting_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844A40BC2D5 FOREIGN KEY (schedule_id) REFERENCES schedule (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844DB77003 FOREIGN KEY (professional_id) REFERENCES professional (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844804F7D71 FOREIGN KEY (consultation_type_id) REFERENCES consultation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844C17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F8442F8B0EB2 FOREIGN KEY (authorization_id) REFERENCES "authorization" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844B0AFEE5E FOREIGN KEY (cancellation_type_id) REFERENCES cancellation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "authorization" ADD CONSTRAINT FK_7A6D8BEFC17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "authorization" ADD CONSTRAINT FK_7A6D8BEFAC8DE0F FOREIGN KEY (service_type_id) REFERENCES service_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bed ADD CONSTRAINT FK_E647FCFF8158330E FOREIGN KEY (bed_type_id) REFERENCES bed_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bed ADD CONSTRAINT FK_E647FCFF54177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch_payer ADD CONSTRAINT FK_2F7A59CEDCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch_payer ADD CONSTRAINT FK_2F7A59CEC17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch_service_type ADD CONSTRAINT FK_1F793463DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch_service_type ADD CONSTRAINT FK_1F793463AC8DE0F FOREIGN KEY (service_type_id) REFERENCES service_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18ADCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_package ADD CONSTRAINT FK_D3CE3EFDC61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_package_detail ADD CONSTRAINT FK_8E28E519E644D1AA FOREIGN KEY (exam_package_id) REFERENCES exam_package (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_package_detail ADD CONSTRAINT FK_8E28E519C61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_permission ADD CONSTRAINT FK_3784F318FE54D947 FOREIGN KEY (group_id) REFERENCES member_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_permission ADD CONSTRAINT FK_3784F318B03A8386 FOREIGN KEY (created_by_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "health_insurance" ADD CONSTRAINT FK_558804DE54CCFBDD FOREIGN KEY (health_insurance_type_id) REFERENCES health_insurance_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "health_insurance" ADD CONSTRAINT FK_558804DE588DA015 FOREIGN KEY (tax_affectation_type_id) REFERENCES "tax_affectation_type" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maintainer_education_level_detail ADD CONSTRAINT FK_D867A8A7D7A5352E FOREIGN KEY (education_level_id) REFERENCES "education_level" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maintainer_origin ADD CONSTRAINT FK_23B5077C703B99FE FOREIGN KEY (origin_type_id) REFERENCES maintainer_origin_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service ADD CONSTRAINT FK_A79F7A1C5C011B5 FOREIGN KEY (figure_id) REFERENCES figure (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service ADD CONSTRAINT FK_A79F7A1CD0EC18BF FOREIGN KEY (budget_item_id) REFERENCES budget_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service ADD CONSTRAINT FK_A79F7A1CAC8DE0F FOREIGN KEY (service_type_id) REFERENCES service_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service ADD CONSTRAINT FK_A79F7A1CBB50891B FOREIGN KEY (sub_company_id) REFERENCES sub_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service ADD CONSTRAINT FK_A79F7A1C3395B1AC FOREIGN KEY (billing_sub_company_id) REFERENCES sub_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service_bed_type ADD CONSTRAINT FK_EEE3D850C61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service_bed_type ADD CONSTRAINT FK_EEE3D8508158330E FOREIGN KEY (bed_type_id) REFERENCES bed_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service_budget_item ADD CONSTRAINT FK_9E9803FBC61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service_budget_item ADD CONSTRAINT FK_9E9803FBA4665449 FOREIGN KEY (surgery_item_id) REFERENCES surgery_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service_service ADD CONSTRAINT FK_D8EE37BEC61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_service_service ADD CONSTRAINT FK_D8EE37BEED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE member_group_membership ADD CONSTRAINT FK_61D5C0D17597D3FE FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE member_group_membership ADD CONSTRAINT FK_61D5C0D19897AAD FOREIGN KEY (member_group_id) REFERENCES member_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu_items ADD CONSTRAINT FK_70B2CA2A727ACA70 FOREIGN KEY (parent_id) REFERENCES menu_items (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "municipality" ADD CONSTRAINT FK_C6F56628E946114A FOREIGN KEY (province_id) REFERENCES "province" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pathology_article ADD CONSTRAINT FK_B24A1BE1541D0E27 FOREIGN KEY (ges_pathology_id) REFERENCES ges_pathology (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payer ADD CONSTRAINT FK_41CB5B99BEA5E0F7 FOREIGN KEY (payer_type_id) REFERENCES payer_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE permission ADD CONSTRAINT FK_E04992AAA76ED395 FOREIGN KEY (user_id) REFERENCES member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE permission ADD CONSTRAINT FK_E04992AAB03A8386 FOREIGN KEY (created_by_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176F54A83F FOREIGN KEY (identification_type_id) REFERENCES "identification_type" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176D7A5352E FOREIGN KEY (education_level_id) REFERENCES "education_level" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176E559F9BF FOREIGN KEY (marital_status_id) REFERENCES "marital_status" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD17622C8FC20 FOREIGN KEY (occupation_id) REFERENCES "occupation" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176E7EEEDB3 FOREIGN KEY (ethnic_group_id) REFERENCES "ethnic_group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176B7850CBD FOREIGN KEY (religion_id) REFERENCES "religion" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176708A0E0 FOREIGN KEY (gender_id) REFERENCES gender (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD1767949DE26 FOREIGN KEY (nacionality_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_address ADD CONSTRAINT FK_2FD0DC08A14E0760 FOREIGN KEY (id_person_id) REFERENCES "person" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_address ADD CONSTRAINT FK_2FD0DC08AE6F181C FOREIGN KEY (municipality_id) REFERENCES "municipality" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_address ADD CONSTRAINT FK_2FD0DC08F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE professional ADD CONSTRAINT FK_B3B573AA9A353316 FOREIGN KEY (specialty_id) REFERENCES specialty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE professional_rate ADD CONSTRAINT FK_CDA906E7DB77003 FOREIGN KEY (professional_id) REFERENCES professional (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE professional_rate ADD CONSTRAINT FK_CDA906E7ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE professional_rate ADD CONSTRAINT FK_CDA906E7C17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "province" ADD CONSTRAINT FK_4ADAD40B98260155 FOREIGN KEY (region_id) REFERENCES "region" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "region" ADD CONSTRAINT FK_F62F176F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519BCC22AD4 FOREIGN KEY (clinic_id) REFERENCES clinic (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FBDB77003 FOREIGN KEY (professional_id) REFERENCES professional (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB804F7D71 FOREIGN KEY (consultation_type_id) REFERENCES consultation_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB6DB2886B FOREIGN KEY (blocking_type_id) REFERENCES blocking_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2AC8DE0F FOREIGN KEY (service_type_id) REFERENCES service_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD29A353316 FOREIGN KEY (specialty_id) REFERENCES specialty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE service_package_detail ADD CONSTRAINT FK_139B51F9621D924B FOREIGN KEY (service_package_id) REFERENCES service_package (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE service_package_detail ADD CONSTRAINT FK_139B51F9C61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE specialty_branch ADD CONSTRAINT FK_89FD01D99A353316 FOREIGN KEY (specialty_id) REFERENCES specialty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE specialty_branch ADD CONSTRAINT FK_89FD01D9DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFCED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFCEEB1F0 FOREIGN KEY (parent_warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE warehouse_medical_service ADD CONSTRAINT FK_E698EAF5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE warehouse_medical_service ADD CONSTRAINT FK_E698EAFC61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE agreement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE appointment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE article_package_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE authorization_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bed_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bed_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE blocking_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE branch_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE branch_payer_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE branch_service_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE budget_item_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "business_activity_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE cancellation_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE clinic_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE consultation_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE cost_center_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE country_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE department_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "education_level_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE eno_pathology_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "ethnic_group_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE exam_package_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exam_package_detail_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE external_referrer_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE figure_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ges_pathology_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE group_permission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "health_insurance_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE health_insurance_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "identification_type_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_doctor_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_education_level_detail_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_insurance_administrator_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_job_position_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_location_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_medical_box_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_origin_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_origin_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "marital_status_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE medical_service_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE medical_service_bed_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE medical_service_budget_item_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE medical_service_service_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE member_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE member_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE menu_items_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "municipality_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE "occupation_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE pathology_article_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE payer_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE payer_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE permission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "person_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE person_address_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE professional_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE professional_rate_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "province_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE "region_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE "religion_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE requesting_company_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reset_password_request_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE room_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE schedule_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE service_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE service_package_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE service_package_detail_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE service_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE gender_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE specialty_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE specialty_branch_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sub_company_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE surgery_item_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "tax_affectation_type_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE tenant_module_permission_override_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tenant_permission_profile_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE treatment_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE warehouse_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE warehouse_medical_service_id_seq CASCADE');
        $this->addSql('ALTER TABLE agreement DROP CONSTRAINT FK_2E655A24C17AD9A9');
        $this->addSql('ALTER TABLE agreement DROP CONSTRAINT FK_2E655A24E3FB3114');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844A40BC2D5');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844DB77003');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844804F7D71');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844C17AD9A9');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F8442F8B0EB2');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844B0AFEE5E');
        $this->addSql('ALTER TABLE "authorization" DROP CONSTRAINT FK_7A6D8BEFC17AD9A9');
        $this->addSql('ALTER TABLE "authorization" DROP CONSTRAINT FK_7A6D8BEFAC8DE0F');
        $this->addSql('ALTER TABLE bed DROP CONSTRAINT FK_E647FCFF8158330E');
        $this->addSql('ALTER TABLE bed DROP CONSTRAINT FK_E647FCFF54177093');
        $this->addSql('ALTER TABLE branch_payer DROP CONSTRAINT FK_2F7A59CEDCD6CC49');
        $this->addSql('ALTER TABLE branch_payer DROP CONSTRAINT FK_2F7A59CEC17AD9A9');
        $this->addSql('ALTER TABLE branch_service_type DROP CONSTRAINT FK_1F793463DCD6CC49');
        $this->addSql('ALTER TABLE branch_service_type DROP CONSTRAINT FK_1F793463AC8DE0F');
        $this->addSql('ALTER TABLE department DROP CONSTRAINT FK_CD1DE18ADCD6CC49');
        $this->addSql('ALTER TABLE exam_package DROP CONSTRAINT FK_D3CE3EFDC61D802A');
        $this->addSql('ALTER TABLE exam_package_detail DROP CONSTRAINT FK_8E28E519E644D1AA');
        $this->addSql('ALTER TABLE exam_package_detail DROP CONSTRAINT FK_8E28E519C61D802A');
        $this->addSql('ALTER TABLE group_permission DROP CONSTRAINT FK_3784F318FE54D947');
        $this->addSql('ALTER TABLE group_permission DROP CONSTRAINT FK_3784F318B03A8386');
        $this->addSql('ALTER TABLE "health_insurance" DROP CONSTRAINT FK_558804DE54CCFBDD');
        $this->addSql('ALTER TABLE "health_insurance" DROP CONSTRAINT FK_558804DE588DA015');
        $this->addSql('ALTER TABLE maintainer_education_level_detail DROP CONSTRAINT FK_D867A8A7D7A5352E');
        $this->addSql('ALTER TABLE maintainer_origin DROP CONSTRAINT FK_23B5077C703B99FE');
        $this->addSql('ALTER TABLE medical_service DROP CONSTRAINT FK_A79F7A1C5C011B5');
        $this->addSql('ALTER TABLE medical_service DROP CONSTRAINT FK_A79F7A1CD0EC18BF');
        $this->addSql('ALTER TABLE medical_service DROP CONSTRAINT FK_A79F7A1CAC8DE0F');
        $this->addSql('ALTER TABLE medical_service DROP CONSTRAINT FK_A79F7A1CBB50891B');
        $this->addSql('ALTER TABLE medical_service DROP CONSTRAINT FK_A79F7A1C3395B1AC');
        $this->addSql('ALTER TABLE medical_service_bed_type DROP CONSTRAINT FK_EEE3D850C61D802A');
        $this->addSql('ALTER TABLE medical_service_bed_type DROP CONSTRAINT FK_EEE3D8508158330E');
        $this->addSql('ALTER TABLE medical_service_budget_item DROP CONSTRAINT FK_9E9803FBC61D802A');
        $this->addSql('ALTER TABLE medical_service_budget_item DROP CONSTRAINT FK_9E9803FBA4665449');
        $this->addSql('ALTER TABLE medical_service_service DROP CONSTRAINT FK_D8EE37BEC61D802A');
        $this->addSql('ALTER TABLE medical_service_service DROP CONSTRAINT FK_D8EE37BEED5CA9E6');
        $this->addSql('ALTER TABLE member_group_membership DROP CONSTRAINT FK_61D5C0D17597D3FE');
        $this->addSql('ALTER TABLE member_group_membership DROP CONSTRAINT FK_61D5C0D19897AAD');
        $this->addSql('ALTER TABLE menu_items DROP CONSTRAINT FK_70B2CA2A727ACA70');
        $this->addSql('ALTER TABLE "municipality" DROP CONSTRAINT FK_C6F56628E946114A');
        $this->addSql('ALTER TABLE pathology_article DROP CONSTRAINT FK_B24A1BE1541D0E27');
        $this->addSql('ALTER TABLE payer DROP CONSTRAINT FK_41CB5B99BEA5E0F7');
        $this->addSql('ALTER TABLE permission DROP CONSTRAINT FK_E04992AAA76ED395');
        $this->addSql('ALTER TABLE permission DROP CONSTRAINT FK_E04992AAB03A8386');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176F54A83F');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176D7A5352E');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176E559F9BF');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD17622C8FC20');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176E7EEEDB3');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176B7850CBD');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176708A0E0');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD1767949DE26');
        $this->addSql('ALTER TABLE person_address DROP CONSTRAINT FK_2FD0DC08A14E0760');
        $this->addSql('ALTER TABLE person_address DROP CONSTRAINT FK_2FD0DC08AE6F181C');
        $this->addSql('ALTER TABLE person_address DROP CONSTRAINT FK_2FD0DC08F92F3E70');
        $this->addSql('ALTER TABLE professional DROP CONSTRAINT FK_B3B573AA9A353316');
        $this->addSql('ALTER TABLE professional_rate DROP CONSTRAINT FK_CDA906E7DB77003');
        $this->addSql('ALTER TABLE professional_rate DROP CONSTRAINT FK_CDA906E7ED5CA9E6');
        $this->addSql('ALTER TABLE professional_rate DROP CONSTRAINT FK_CDA906E7C17AD9A9');
        $this->addSql('ALTER TABLE "province" DROP CONSTRAINT FK_4ADAD40B98260155');
        $this->addSql('ALTER TABLE "region" DROP CONSTRAINT FK_F62F176F92F3E70');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519BCC22AD4');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FBDB77003');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FB804F7D71');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FB6DB2886B');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD2AC8DE0F');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD29A353316');
        $this->addSql('ALTER TABLE service_package_detail DROP CONSTRAINT FK_139B51F9621D924B');
        $this->addSql('ALTER TABLE service_package_detail DROP CONSTRAINT FK_139B51F9C61D802A');
        $this->addSql('ALTER TABLE specialty_branch DROP CONSTRAINT FK_89FD01D99A353316');
        $this->addSql('ALTER TABLE specialty_branch DROP CONSTRAINT FK_89FD01D9DCD6CC49');
        $this->addSql('ALTER TABLE warehouse DROP CONSTRAINT FK_ECB38BFCED5CA9E6');
        $this->addSql('ALTER TABLE warehouse DROP CONSTRAINT FK_ECB38BFCEEB1F0');
        $this->addSql('ALTER TABLE warehouse_medical_service DROP CONSTRAINT FK_E698EAF5080ECDE');
        $this->addSql('ALTER TABLE warehouse_medical_service DROP CONSTRAINT FK_E698EAFC61D802A');
        $this->addSql('DROP TABLE agreement');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE article_package');
        $this->addSql('DROP TABLE "authorization"');
        $this->addSql('DROP TABLE bed');
        $this->addSql('DROP TABLE bed_type');
        $this->addSql('DROP TABLE blocking_type');
        $this->addSql('DROP TABLE branch');
        $this->addSql('DROP TABLE branch_payer');
        $this->addSql('DROP TABLE branch_service_type');
        $this->addSql('DROP TABLE budget_item');
        $this->addSql('DROP TABLE "business_activity"');
        $this->addSql('DROP TABLE cancellation_type');
        $this->addSql('DROP TABLE clinic');
        $this->addSql('DROP TABLE consultation_type');
        $this->addSql('DROP TABLE cost_center');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE "education_level"');
        $this->addSql('DROP TABLE eno_pathology');
        $this->addSql('DROP TABLE "ethnic_group"');
        $this->addSql('DROP TABLE exam_package');
        $this->addSql('DROP TABLE exam_package_detail');
        $this->addSql('DROP TABLE external_referrer');
        $this->addSql('DROP TABLE figure');
        $this->addSql('DROP TABLE ges_pathology');
        $this->addSql('DROP TABLE group_permission');
        $this->addSql('DROP TABLE "health_insurance"');
        $this->addSql('DROP TABLE health_insurance_type');
        $this->addSql('DROP TABLE "identification_type"');
        $this->addSql('DROP TABLE maintainer_doctor_type');
        $this->addSql('DROP TABLE maintainer_education_level_detail');
        $this->addSql('DROP TABLE maintainer_insurance_administrator');
        $this->addSql('DROP TABLE maintainer_job_position');
        $this->addSql('DROP TABLE maintainer_location');
        $this->addSql('DROP TABLE maintainer_medical_box');
        $this->addSql('DROP TABLE maintainer_origin');
        $this->addSql('DROP TABLE maintainer_origin_type');
        $this->addSql('DROP TABLE "marital_status"');
        $this->addSql('DROP TABLE medical_service');
        $this->addSql('DROP TABLE medical_service_bed_type');
        $this->addSql('DROP TABLE medical_service_budget_item');
        $this->addSql('DROP TABLE medical_service_service');
        $this->addSql('DROP TABLE member');
        $this->addSql('DROP TABLE member_group_membership');
        $this->addSql('DROP TABLE member_group');
        $this->addSql('DROP TABLE menu_items');
        $this->addSql('DROP TABLE "municipality"');
        $this->addSql('DROP TABLE "occupation"');
        $this->addSql('DROP TABLE pathology_article');
        $this->addSql('DROP TABLE payer');
        $this->addSql('DROP TABLE payer_type');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE "person"');
        $this->addSql('DROP TABLE person_address');
        $this->addSql('DROP TABLE professional');
        $this->addSql('DROP TABLE professional_rate');
        $this->addSql('DROP TABLE "province"');
        $this->addSql('DROP TABLE "region"');
        $this->addSql('DROP TABLE "religion"');
        $this->addSql('DROP TABLE requesting_company');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE schedule');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE service_package');
        $this->addSql('DROP TABLE service_package_detail');
        $this->addSql('DROP TABLE service_type');
        $this->addSql('DROP TABLE "setting"');
        $this->addSql('DROP TABLE gender');
        $this->addSql('DROP TABLE specialty');
        $this->addSql('DROP TABLE specialty_branch');
        $this->addSql('DROP TABLE sub_company');
        $this->addSql('DROP TABLE surgery_item');
        $this->addSql('DROP TABLE "tax_affectation_type"');
        $this->addSql('DROP TABLE tenant_module_permission_override');
        $this->addSql('DROP TABLE tenant_permission_profile');
        $this->addSql('DROP TABLE treatment_type');
        $this->addSql('DROP TABLE warehouse');
        $this->addSql('DROP TABLE warehouse_medical_service');
    }
}
